### ISSUE TITLE
依赖下载不下来啊

### ISSUE THREAD

**Issue by shingohu** [CaiJingLong/flutter_ijkplayer#1]
ERROR: Unable to resolve dependency for ':flutter_ijkplayer@debug/compileClasspath': Could not resolve tv.danmaku.ijk.media:ijkplayer-java:0.8.8.

**Comment by CaiJingLong** [comment]
这个是ijkplayer官方的依赖源,我这里对于java端的代码没有进行任何修改
如果你可以使用vpn,可以尝试使用vpn

或尝试使用阿里云的jcenter镜像

**Comment by shingohu** [comment]
好的，我看下
另外数据源的设置可以考虑创建几个工厂方法

**Comment by CaiJingLong** [comment]
阿里云镜像设置方法可以查看这里
https://help.aliyun.com/document_detail/102512.html?spm=a2c40.aliyun_maven_repo.0.0.36183054sxDdA1

**Comment by shingohu** [comment]
@CaiJingLong 感谢,刚设置后就可以了,正在看能不能使用,顺便问下ijk 支持 wmv和avi 不,官方不支持，只能更换其他的了

**Comment by CaiJingLong** [comment]
目前应该是不支持的

**Comment by CaiJingLong** [comment]
android 端使用的是 https://github.com/CarGuo/GSYVideoPlayer 中的so库 
这里有说明 https://github.com/CarGuo/GSYVideoPlayer/blob/master/doc/DECODERS.md
目前支持的封装格式看这里 https://github.com/CarGuo/GSYVideoPlayer/blob/master/module-lite.sh#L89-L104

如果你有额外需要只能是自己编译so库

**Comment by CaiJingLong** [comment]
其实更加建议是自定义配置,根据自己的需求来编译ffmpeg,这样可以有效降低apk/ipa的体积

**Comment by shingohu** [comment]
他这个应该也是没支持wmv,avi的。对于客户来说肯定是什么格式都支持最好不过了。不过还是表示感谢
star了
