### ISSUE TITLE
android release播放直播源闪退

### ISSUE THREAD

**Issue by zf19820621** [CaiJingLong/flutter_ijkplayer#102]
版本0.3.1，debug不会，release打开直播（不一定能播放）就闪退，一旦出错下次必定闪退，adb logcat 如下：
![QQ截图20190715025344](https://user-images.githubusercontent.com/31683048/61188144-85737480-a6ad-11e9-9dd1-a85015635c6d.png)
![QQ截图20190715025415](https://user-images.githubusercontent.com/31683048/61188145-85737480-a6ad-11e9-967a-bd4b774759af.png)

**Comment by zf19820621** [comment]
目前使用的datasource，主要是rtmp，flv，请问目前项目中的so都支持这些格式吧

**Comment by CaiJingLong** [comment]
crash的原因看上去是so库没有打入apk, 建议你检查一下apk内包含的so库.
可以把apk拖入android studio中查看.

**Comment by zf19820621** [comment]
不是有的

在 2019-07-15 16:31:48，"Caijinglong" <notifications@github.com> 写道：


crash的原因看上去是so库没有打入apk, 建议你检查一下apk内包含的so库.
可以把apk拖入android studio中查看.

**Comment by zf19820621** [comment]
我改成armeabi-v7a了，里面有那几个so的

**Comment by CaiJingLong** [comment]
提供一个打包好的apk?
另外, 提供一个可复现的最小代码仓库,  我可以试试看能否帮助你定位问题.

**Comment by zf19820621** [comment]
知道问题在哪了，一个是我android proguard中没有添加ijk的保留配置， 还有一个是arm64，和armeabi flutter项目只能生成一个libflutter.so，所以有的手机会闪退，谢谢作者
