### ISSUE TITLE
[Bug]同一个控制器播放完第一个是后 修改第二个 视频时报错

### ISSUE THREAD

**Issue by yh4922** [CaiJingLong/flutter_ijkplayer#106]
同一个控制器播放完第一个是后 修改第二个 视频时报错
`MissingPluginException(No implementation found for method seekTo on channel top.kikt/ijkplayer/4`

播放第一个视频后 使用
`mediaController.setNetworkDataSource(playVideoUrl, autoPlay: true);`
切换播放源时 报错 
在debug 跳过错误后可以正常播放 

**日志**
MissingPluginException(No implementation found for method seekTo on channel top.kikt/ijkplayer/4

**flutter 版本**
Flutter (Channel stable, v1.2.1, on Microsoft Windows [Version 10.0.17763.475], locale zh-CN)
Android toolchain - develop for Android devices (Android SDK version 28.0.3)
Android Studio (version 3.2)
Connected device (1 available)

**截图**
![微信图片_20190719112641.png](https://i.loli.net/2019/07/19/5d3138887fba542159.png)

**Comment by CaiJingLong** [comment]
应该是线程问题造成的
请帮忙留言是 android还是ios, 我后续会尽量定位问题.

**Comment by CaiJingLong** [comment]
应该是线程问题造成的
请帮忙留言是 android还是ios, 我后续会尽量定位问题.

**Comment by yh4922** [comment]
android 的
