### ISSUE TITLE
[Need help]植入自己编译的库时出错了

### ISSUE THREAD

**Issue by bear-zyy** [CaiJingLong/flutter_ijkplayer#107]
在pubspec.yaml文件中
 设置
 flutter_ijkplayer:
      path: ./flutter_ijkplayer

这里出错了，不知道是什么原因

**Comment by bear-zyy** [comment]
提示  
Could not find a file named "pubspec.yaml" in "/Users/zyy/Desktop/flutterijktest".
pub get failed (66)

**Comment by CaiJingLong** [comment]
项目依赖的问题, 请自行查看dart官方的说明, 确定目录结构的问题.
