### ISSUE TITLE
[Bug] Can't get screenshot.

### ISSUE THREAD

**Issue by yyaini112** [CaiJingLong/flutter_ijkplayer#111]
git clone 项目,在android 9,截取视频画面模块出现,D/ijkplayer-jni(12368): current frame is null.

**Comment by CaiJingLong** [comment]
单独看说明无法确定问题.
截图本身只有在播放的过程中有效, 播放前无法获取视频帧, 播放后视频帧信息可能会被清空.

**Comment by yyaini112** [comment]
确实是在播放过程中.手机端无法截取视频画面.我打印了视频信息显示isPlaying=true.不知道这样能不能说明问题?

I/NotifyChannel(27406): completion buffer update {duration=244.203, tcpSpeed=126840, isPlaying=true, outputFps=25.0, currentPosition=17.916, width=600, degree=0, height=338} 15
I/NotifyChannel(27406): completion buffer update {duration=244.203, tcpSpeed=117727, isPlaying=true, outputFps=25.0, currentPosition=18.437, width=600, degree=0, height=338} 16
I/flutter (27406): 打印控制器信息=====================
I/flutter (27406): {"duration":244.203,"tcpSpeed":123376,"isPlaying":true,"outputFps":25.0,"currentPosition":18.771,"width":600,"degree":0,"height":338}
D/ijkplayer-jni(27406): current frame is null
I/flutter (27406): 打印图片=====================
I/flutter (27406): null
I/NotifyChannel(27406): completion buffer update {duration=244.203, tcpSpeed=126438, isPlaying=true, outputFps=25.0, currentPosition=18.958, width=600, degree=0, height=338} 16
I/NotifyChannel(27406): completion buffer update {duration=244.203, tcpSpeed=139424, isPlaying=true, outputFps=25.0, currentPosition=19.473, width=600, degree=0, height=338} 17

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/61778431-512c5080-ae31-11e9-9cb4-89cfc2cdb485.png)

单纯从代码看, 只有这个视频帧的数据没有获取到的时候 才会在jni层输出这个日志, 而这个帧数据理论上不会为空, 因为空了以后界面上就没有画面可以显示了

---

另: 我自己使用的也是Android 9.0的设备, 没有发现无法截屏这个问题

**Comment by CaiJingLong** [comment]
```dart
mediaController.setIjkPlayerOptions(
      [
        TargetPlatform.android,
      ],
      [
        IjkOption(IjkOptionCategory.player, "mediacodec", 0),
      ],
    );
```
Use in before `setDatasource `.

Because the screenshot only support software decode.
