### ISSUE TITLE
全屏的时候快进和后退还是竖屏的，图片显示也是，手势音量和亮度正常

### ISSUE THREAD

**Issue by batdkuwlh** [CaiJingLong/flutter_ijkplayer#112]
全屏的时候快进和后退还是竖屏的，图片显示也是，用的是默认模式FullScreenType.rotateBox

**Comment by sosopop** [comment]
IjkPlayer(
                    mediaController: _videoController,
                    controllerWidgetBuilder: (mediaController) {
                      return DefaultIJKControllerWidget(
                          controller: mediaController,
                          fullScreenType: FullScreenType.rotateScreen); // 自定义
                    })
