### ISSUE TITLE
想要在视频界面手动画矩形框，改了一次源码没能实现，请问有什么思路可以提供的吗？

### ISSUE THREAD

**Issue by yyaini112** [CaiJingLong/flutter_ijkplayer#115]
想要在视频界面手动画矩形框，改了一次源码没能实现，请问有什么思路可以提供的吗？

**Comment by CaiJingLong** [comment]
没看懂 什么矩形框?

**Comment by yyaini112** [comment]
![image](https://user-images.githubusercontent.com/17791418/62020441-7afcc300-b1f5-11e9-90fe-23ec7eb62911.png)
像这种，在视频中手动画矩形，

**Comment by CaiJingLong** [comment]
你是想修改视频帧 还是说仅仅是想类似于 Stack 的方式 在界面上单独放一个带边框的Widget

**Comment by yyaini112** [comment]
第二种方式，带一个边框的widget就好了。

**Comment by CaiJingLong** [comment]
视频帧的修改我确实帮不了你  那个肯定需要hook到c代码

这个widget的话 你用Stack包上IjkPlayer和一个自定义的widget, 然后这个自定义的widget接收手势然后修改界面就行了...

**Comment by yyaini112** [comment]
嗯呢，感谢你，能否加一下微信号 Kzichun  在修改源码的过程中，需要请教您。

**Comment by yyaini112** [comment]
现在可以从空白区域往上画矩形框，但从视频区域画矩形框确没有反应（关闭了    this.verticalGesture = false, this.horizontalGesture = false,  也一样）。请问，如何实现从从视频区域也能画矩形框呢！

![](https://static.dingtalk.com/media/lALPBE1XYO-MmOLNCHDNBDg_1080_2160.png_620x10000q90g.jpg)

**Comment by CaiJingLong** [comment]
可能是手势冲突, `IJKPlayer` 位置的控件不能响应其他的手势.
给IjkPlayer这个控件外套一个 IgnorePointer , 通过控制ignoring 属性来控制是否响应手势. 
例如: 当你想要画框的时候, 把 `ignoring` 设置为true, 画框结束后, 把这个`ignoring` 设置为false.
