### ISSUE TITLE
cannot play hls after playing rtsp stream

### ISSUE THREAD

**Issue by andpark** [CaiJingLong/flutter_ijkplayer#116]
I've built ios framework with rtsp support

It plays hls and rtsp.
It plays rtsp after playing hls but It cannot play hls after playing rtsp.

If I don't play rtsp, It can play hls again and again. but when I play rtsp stream. It no longer plays hls  until I restart the application.

I did some more investigation and I found this.
It fails to open input on "avformat_open_input" with error code "-1094995529".

for more information.
"avformat_open_input" does not open segment file url(ts file) after playing rtsp stream.
mp4 files something like "http://techslides.com/demos/sample-videos/small.mp4" opened normally.
(it opens and plays ts segment file before opening rtsp stream)

**Comment by CaiJingLong** [comment]
This does not look like this plugin problem
You can try asking in [bilibili/ijkplayer](https://github.com/bilibili/ijkplayer/issues).

**Comment by andpark** [comment]
> This does not look like this plugin problem
> You can try asking in [bilibili/ijkplayer](https://github.com/bilibili/ijkplayer/issues).

Yes, I think so. Thank you.
