### ISSUE TITLE
[Need help] Replay Video Automatically 

### ISSUE THREAD

**Issue by AbedRabaia** [CaiJingLong/flutter_ijkplayer#117]
Hello Everyone 

Am trying to make video autoreply after finishing, I added that to the player options and it's not working, if anyone could help me solve this, please 

<img width="927" alt="Screen Shot 2019-07-30 at 1 04 33 PM" src="https://user-images.githubusercontent.com/7426123/62120811-0300cc80-b2cb-11e9-815c-690e21d5a11e.png">

**Comment by CaiJingLong** [comment]
Try to swap the order of setOptions and setDataSource?

Of course, this may not be the problem. But options are only available if they are set before setDataSource.
