### ISSUE TITLE
关于ijk全屏播放的一些需求建议

### ISSUE THREAD

**Issue by zhangbaolin** [CaiJingLong/flutter_ijkplayer#118]
作者你好 ，在使用这个插件的时候遇到了一些问题：1.滑动屏幕调节音量 和 亮度  这个控制器无法控制。2.在全屏播放的时候调节  音量  亮度  快进、回放一些滑动屏幕的操作还是竖屏时候的一些控制状态，希望在全屏时候那些控制状态能够改变。希望能够得到作者的帮助，不胜感激!

**Comment by CaiJingLong** [comment]
你可以尝试master的分支
全屏的手势行为的异常我修复了, 暂时没有往pub传

**Comment by zhangbaolin** [comment]
那是否有办法获取到 亮度调节  音量调节的手势事件呢，并且成为可控的呢。

**Comment by zhangbaolin** [comment]
全屏的手势行为的异常,能否请您在更新一个版本呢，谢谢了

**Comment by CaiJingLong** [comment]
Version 0.3.2 is uploaded.
