### ISSUE TITLE
需要一个可以释放资源但不销毁mediaController的方法

### ISSUE THREAD

**Issue by batdkuwlh** [CaiJingLong/flutter_ijkplayer#119]
在视频列表当中，如果只是暂停不释放内存，会占用大量内存导致APP崩溃。
// 这里要说明,ijkplayer的stop会释放资源,导致play不能使用,需要重新准备资源,所以这里其实采用的是回到进度条开始,并暂停
await controller.stop(); 这个方法好像不会释放内存。
尝试过在视频列表中调用mediaController.dispose()来释放内存，然后再设置新的mediaController, 会出现黑屏，log显示视频在解析播放

**Comment by batdkuwlh** [comment]
await controller.stop(); 这个方法可以修改为保存当前进度，并释放内存，可能会更有用一些

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/62268985-3591fd00-b464-11e9-8d9e-3dca52efd6e1.png)
"因为" bilibili/IjkPlayer的stop方法会释放资源导致不能播放, 所以插件采用的是回到进度条开始, 并暂停,  所以不会释放资源
----

![image](https://user-images.githubusercontent.com/14145407/62269060-7d188900-b464-11e9-83ba-f8a96642cc15.png)

reset才是需要复用controller的释放资源的方法

dispose会释放资源 ,且该controller不再可用

**Comment by CaiJingLong** [comment]
释放资源Readme : https://github.com/CaiJingLong/flutter_ijkplayer#%E9%87%8A%E6%94%BE%E8%B5%84%E6%BA%90

**Comment by CaiJingLong** [comment]
这种"保存进度"的方法应该是业务调用方实现, 播放器不应该有"自动保存"的概念.

**Comment by batdkuwlh** [comment]
await controller.reset(); //才看到这个方法，没事了
