### ISSUE TITLE
[Bug]关于我在播放http和https时有一部分视频无法播放的问题

### ISSUE THREAD

**Issue by senmao1994** [CaiJingLong/flutter_ijkplayer#121]
**描述一下你遇到的 bug**
在开发时突然发现一个问题，点播视频里：播放地址是http开头的，那在播放后退出页面或者更换成https开头的视频是无法播放的。反之也是如此

**重现 bug**

通过什么样的步骤可以重现:
用一个http或者https开头的播放后，更换或者退出都无法再播放https或者http的视频
我在官方提供的demo里也试了一下 也有同样的问题出现，销毁和初始化我都是按照demo的方法做的，可以帮我找找原因吗，谢谢

**日志**
V/IJKMEDIA(22909): setDataSource: path https://k12online.oss-cn-shenzhen.aliyuncs.com/vipgo/record/vipgo/ycb-1/ycb-jyfzzl.mp4
D/IJKMEDIA(22909): ijkmp_set_data_source(url="https://k12online.oss-cn-shenzhen.aliyuncs.com/vipgo/record/vipgo/ycb-1/ycb-jyfzzl.mp4")
D/IJKMEDIA(22909): ijkmp_set_data_source(url="https://k12online.oss-cn-shenzhen.aliyuncs.com/vipgo/record/vipgo/ycb-1/ycb-jyfzzl.mp4")=0
D/IJKMEDIA(22909): IjkMediaPlayer_prepareAsync
D/IJKMEDIA(22909): ijkmp_prepare_async()
I/IJKMEDIA(22909): ===== versions =====
I/IJKMEDIA(22909): ijkplayer    : k0.8.8-15-ge7fde118
I/IJKMEDIA(22909): FFmpeg       : ff3.4--ijk0.8.7--20180103--001
I/IJKMEDIA(22909): libavutil    : 55.78.100
I/IJKMEDIA(22909): SDL_RunThread: [25038] ff_msg_loop
I/IJKMEDIA(22909): libavcodec   : 57.107.100
I/IJKMEDIA(22909): libavformat  : 57.83.100
I/IJKMEDIA(22909): libswscale   : 4.8.100
D/IJKMEDIA(22909): message_loop
I/IJKMEDIA(22909): libswresample: 2.9.100
I/IJKMEDIA(22909): ===== options =====
I/IJKMEDIA(22909): player-opts : reconnect                    = 5
I/IJKMEDIA(22909): player-opts : framedrop                    = 5
I/IJKMEDIA(22909): player-opts : enable-accurate-seek         = 1
I/IJKMEDIA(22909): player-opts : mediacodec                   = 1
I/IJKMEDIA(22909): player-opts : packet-buffering             = 1
I/IJKMEDIA(22909): player-opts : soundtouch                   = 1
I/IJKMEDIA(22909): player-opts : start-on-prepared            = 1
I/IJKMEDIA(22909): format-opts : ijkapplication               = 516400433184
I/IJKMEDIA(22909): format-opts : ijkiomanager                 = 516400397440
I/IJKMEDIA(22909): format-opts : fflags                       = fastseek
I/IJKMEDIA(22909): ===================
D/IJKMEDIA(22909): ijkmp_prepare_async()=0
I/IJKMEDIA(22909): SDL_RunThread: [25039] ff_vout
D/IJKMEDIA(22909): FFP_MSG_FLUSH:
I/IJKMEDIA(22909): SDL_RunThread: [25040] ff_read
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(22909): onNativeInvoke 1
I/NotifyChannel(22909): onNativeInvoke 1
I/IJKMEDIA(22909): Hit DNS cache hostname = k12online.oss-cn-shenzhen.aliyuncs.com
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(22909): onNativeInvoke 131073
I/NotifyChannel(22909): onNativeInvoke 131073
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(22909): onNativeInvoke 131074
I/NotifyChannel(22909): onNativeInvoke 131074
E/IJKMEDIA(22909): error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
I/tv.danmaku.ijk.media.player.IjkMediaPlayer(22909): onNativeInvoke 2
I/NotifyChannel(22909): onNativeInvoke 2
E/IJKMEDIA(22909): https://k12online.oss-cn-shenzhen.aliyuncs.com/vipgo/record/vipgo/ycb-1/ycb-jyfzzl.mp4: I/O error
I/IJKMEDIA(22909): SDL_JNI_DetachThreadEnv: [25040]
D/IJKMEDIA(22909): FFP_MSG_ERROR: 0
E/tv.danmaku.ijk.media.player.IjkMediaPlayer(22909): Error (-10000,0)
I/NotifyChannel(22909): onError -10000 , extra = 0
I/NotifyChannel(22909): completion {duration=0.0, tcpSpeed=58, isPlaying=false, outputFps=0.0, currentPosition=0.0, width=0, degree=0, height=0}

**flutter 版本**
使用 `$ flutter doctor -v` 并粘贴详细的信息到这里,如果是特定机型的 bug,请包含设备信息

```bash

```

**插件版本**

**截图**
如果有,请截图
![image](https://user-images.githubusercontent.com/50578587/62285375-0db49080-b488-11e9-96fb-7d981ed4a7f9.png)

**Comment by senmao1994** [comment]
flutter版本号 
[√] Flutter
(Channel stable, v1.7.8+hotfix.4, on Microsoft Windows [Version 10.0.15063], locale zh-CN)                                                                                                  • Flutter version 1.7.8+hotfix.4 at D:\flutter                                                                                                                                                       • Framework revision 20e59316b8 (13 days ago), 2019-07-18 20:04:33 -0700                                                                                                                             • Engine
revision fee001c93f                                                                                                                                                                         • Dart version 2.4.0
flutter_ijkplayer: ^0.3.1

**Comment by andpark** [comment]
I'm not sure but, I think it is related to this https://github.com/bilibili/ijkplayer/issues/4810

I solved it using `options.add(IjkOption(IjkOptionCategory.format, "dns_cache_clear", 1));`

and these options might helpful.
```
options.add(IjkOption(IjkOptionCategory.player, "max-buffer-size", 1024*1024));
options.add(IjkOption(IjkOptionCategory.player, "packet-buffering", 0));
options.add(IjkOption(IjkOptionCategory.player, "min-frames", 5));
```

**Comment by CaiJingLong** [comment]
Emm, you maybe find issue from [bilibili/ijkplayer](https://github.com/bilibili/ijkplayer/issues/).

Because , the player engine problem is not solved by the plugin.

**Comment by senmao1994** [comment]
> I'm not sure but, I think it is related to this [bilibili/ijkplayer#4810](https://github.com/bilibili/ijkplayer/issues/4810)
> 
> I solved it using `options.add(IjkOption(IjkOptionCategory.format, "dns_cache_clear", 1));`
> 
> and these options might helpful.
> 
> ```
> options.add(IjkOption(IjkOptionCategory.player, "max-buffer-size", 1024*1024));
> options.add(IjkOption(IjkOptionCategory.player, "packet-buffering", 0));
> options.add(IjkOption(IjkOptionCategory.player, "min-frames", 5));
> ```

thanks，I can try。

**Comment by senmao1994** [comment]
> Emm, you maybe find issue from [bilibili/ijkplayer](https://github.com/bilibili/ijkplayer/issues/).
> 
> Because , the player engine problem is not solved by the plugin.

thank you

**Comment by CaiJingLong** [comment]
I'll close the issue. If the above friend's option doesn't solve your problem, please re-open it.

**Comment by CaiJingLong** [comment]
```dart
options.add(IjkOption(IjkOptionCategory.format, "dns_cache_clear", 1));
```
如果你还有这个问题,可以试试添加这个选项.
