### ISSUE TITLE
[Need help] stretch video to fit screen

### ISSUE THREAD

**Issue by andpark** [CaiJingLong/flutter_ijkplayer#123]
I need to stretch video frame to fit screen but I can't find way to do it.
Maybe there is player option to do that, but I can't find it.

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_ijkplayer/blob/6765940fe0376893a4575802d1c30dc0a836f2da/README-EN.md#L415-L428

Default impl is https://github.com/CaiJingLong/flutter_ijkplayer/blob/2f0f6ce7f13cc474593586a6a65313f2006fecee/lib/src/widget/ijkplayer_builder.dart#L26-L86

**Comment by CaiJingLong** [comment]
You can try to customize the texture part and use `FittedBox` with your own implementation.

Even if your resource is just a pure music without a video part, here you can put Widgets like lyrics, which are done according to your own situation.

**Comment by andpark** [comment]
@CaiJingLong Thank you.
Right before your answer is posted, I solved it by wrapping IjkPlayer Widget with Transform widget and scaled it.
I could calculate scaleX, scaleY using original video frame size from 'VideoInfo'.

**Comment by CaiJingLong** [comment]
There are many ways, you can do it according to your own ideas.
