### ISSUE TITLE
[Bug] screenShot does not work on android

### ISSUE THREAD

**Issue by andpark** [CaiJingLong/flutter_ijkplayer#124]
`IjkMediaController.screenShot` returns always null on android device.
but it works on ios.
There is no error message or log..

**Comment by CaiJingLong** [comment]
dup of #111 .

**Comment by CaiJingLong** [comment]
```dart
mediaController.setIjkPlayerOptions(
      [
        TargetPlatform.android,
      ],
      [
        IjkOption(IjkOptionCategory.player, "mediacodec", 0),
      ],
    );
```
Use in before `setDatasource `.

Because the screenshot only support software decode.
