### ISSUE TITLE
全屏时候快进 后退  手势事件

### ISSUE THREAD

**Issue by zhangbaolin** [CaiJingLong/flutter_ijkplayer#126]
你好 ，在全屏时候快进  后退的手势事件 好像有点不太灵敏， 往前面滑动的时候有时会判断成后退。反之亦，有什么解决的办法吗。

**Comment by CaiJingLong** [comment]
手势是一个默认行为但写法是自己实现的, 如果你觉得不灵敏或者不符合预期, 可能需要自行使用自定义UI控制器的方案进行定义

**Comment by zhangbaolin** [comment]
在竖屏播放的时候  快进 快退 滑动时候是正常的，我所说的那种不灵敏是指，例如：横屏播放的时候向前滑动了很大一段距离 但是却只快进了几秒，有时候向前滑动需要快进的时候，还会变成负数。希望您能注意到这个问题。谢谢啦

**Comment by zhangbaolin** [comment]
您好  现在使用您的播放器插件，目前还有我上面描述的那一个问题就是全屏的时候快进  后退手势的这个问题，另外希望您能留下一个联系方式，麻烦了您那么多次，希望能给您表示感谢！我的QQ572352296 亦是邮箱  谢谢啦
