### ISSUE TITLE
怎么在ios上使用该插件，还是不太懂，有详细的解释没

### ISSUE THREAD

**Issue by wssGod** [CaiJingLong/flutter_ijkplayer#127]
[!] CocoaPods could not find compatible versions for pod "FlutterIJK":
  In Podfile:
    flutter_ijkplayer (from `.symlinks/plugins/flutter_ijkplayer/ios`) was resolved to 0.0.1, which depends on
      FlutterIJK (~> 0.1.0)

None of your spec sources contain a spec satisfying the dependency: `FlutterIJK (~> 0.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by CaiJingLong** [comment]
感觉提示的比较明白,  如果看不明白建议机翻一下

先进入ios目录
cd ios
然后更新 pod 仓库的索引
`pod repo update ` 或 `pod install --repo-update`

这个过程如果没有代理翻墙时间会很长

这个是ios cocoapod库的使用范畴 和本库无关
