### ISSUE TITLE
[Feature request]全屏的时候，状态栏存在

### ISSUE THREAD

**Issue by iperfectapp** [CaiJingLong/flutter_ijkplayer#131]
![image](https://user-images.githubusercontent.com/3021764/63877807-e5727000-c9fa-11e9-8e87-e99784261f3f.png)
安卓效果

![image](https://user-images.githubusercontent.com/3021764/63877834-f28f5f00-c9fa-11e9-8a65-c6c86d9d412b.png)
苹果效果

请问有办法隐藏状态栏吗？

**Comment by CaiJingLong** [comment]
目前插件中没有单独隐藏状态栏的通知, flutter 中是否有这个方法我需要查找下 api 或 engine 源码.

**Comment by CaiJingLong** [comment]
我刚刚确认了一下, ios部分没有提供对应的方法来动态切换, 这部分对应的解决方案是自定义一个 控制器继承`FlutterViewController`来实现, 或等 flutter 官方修改源码.
android 部分, 根据我的经验来看, 是可以实现的, 但不能保证一定适用于所有rom和版本号

**Comment by CaiJingLong** [comment]
ios部分呢, 则是引擎中需要添加一个回调 / 通知接收器, 可以修改`prefersStatusBarHidden` 的返回值来实现

https://github.com/flutter/engine/blob/11e3ade157dbe459c1fc83d773ad7db358a1e46b/shell/platform/darwin/ios/framework/Source/FlutterViewController.mm

**Comment by iperfectapp** [comment]
非常感谢，我试试

**Comment by CaiJingLong** [comment]
@iperfectapp 这个代码不是在dart里的 是在原生中的...
你需要通过methodChannel调用,然后在原生中修改

**Comment by iperfectapp** [comment]
感觉有点麻烦了，ijkplayer怎么实现的呢

**Comment by 719733328** [comment]
@iperfectapp  fullScreenType改成旋转屏幕就可以了

`IjkPlayer(
            mediaController: controller,
            controllerWidgetBuilder: (mediaController) {
              return DefaultIJKControllerWidget(controller: mediaController, fullScreenType: FullScreenType.rotateScreen);
            }
        )`

**Comment by iperfectapp** [comment]
谢谢




| |
123
邮箱：newton520@163.com
|

签名由 网易邮箱大师 定制

在2019年09月16日 14:50，719733328 写道：

@iperfectapp fullScreenType改成旋转屏幕就可以了

IjkPlayer( mediaController: controller, controllerWidgetBuilder: (mediaController) { return DefaultIJKControllerWidget(controller: mediaController, fullScreenType: FullScreenType.rotateScreen); } )

**Comment by CaiJingLong** [comment]
文档中有写 目前有两种方式来实现旋转屏幕 一种是使用iOS提供的转屏方式
这种方式如果app设置强制竖屏会crash, 所以不是默认行为. 
目前默认行为是旋转ijkplayer, 也可以如同上面的朋友说的, 修改`fullScreenType`的方式来实现.

**Comment by nancy54264** [comment]
> @iperfectapp fullScreenType改成旋转屏幕就可以了
> 
> `IjkPlayer( mediaController: controller, controllerWidgetBuilder: (mediaController) { return DefaultIJKControllerWidget(controller: mediaController, fullScreenType: FullScreenType.rotateScreen); } )`

试了这样改，虽然纵屏的顶部状态栏没有了，，但是横屏的状态栏还在
