### ISSUE TITLE
[Bug]在使用列表播放的时候，几个视频可以同时播放

### ISSUE THREAD

**Issue by ljackChen001** [CaiJingLong/flutter_ijkplayer#132]
**描述一下你遇到的 bug**
描述一下你的 bug
在使用列表播放的时候，几个视频可以同时播放
**重现 bug**

通过什么样的步骤可以重现:

1. 点击第一个列表视频的播放按钮开始播放然后再播放第三个，再去点第一个播放视频 ，就会同时播放视频

**日志**

```

```

**flutter 版本**
使用 `$ flutter doctor -v` 并粘贴详细的信息到这里,如果是特定机型的 bug,请包含设备信息

```bash

```

**插件版本**

**截图**
如果有,请截图
![image](https://user-images.githubusercontent.com/13534229/64102407-7f8f3b00-cda2-11e9-886a-31e995a83dba.png)

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/65409057-5a2da400-de19-11e9-95ff-9c2578db500f.png)
