### ISSUE TITLE
[Bug]在iOS上面播放卡顿，android不卡顿

### ISSUE THREAD

**Issue by iperfectapp** [CaiJingLong/flutter_ijkplayer#133]
这是在iOS上面的测试效果：

http://47.97.206.17:88/test.mp4

**Comment by iperfectapp** [comment]
播放链接：https://meiju9.whetyy.com/20190903/Pq8VDBIu/index.m3u8

其实任何链接都是一样的

**Comment by befovy** [comment]
测试播放地址 https://yanzishan.shuhu-zuida.com/20190828/15170_b9c98296/index.m3u8

CaiJingLong/flutter_ijkplayer 实际刷新帧率 3
![image](https://user-images.githubusercontent.com/51129600/64319445-f3be1e80-cfee-11e9-80c1-b918ca97649a.png)


 https://github.com/befovy/fijkplayer （我开源的flutter ijkplayer 插件）刷新帧率 25， 播放流畅。
![image](https://user-images.githubusercontent.com/51129600/64319651-7b0b9200-cfef-11e9-9a30-c8d302c72417.png)

**Comment by infiraydevice** [comment]
确实ios卡顿明显

**Comment by CaiJingLong** [comment]
我尝试了一下  自动播放的视频确实有这个问题 应该是ios端的CADisplayLink 没有启动的原因
暂停再继续播放帧数恢复正常.

**Comment by CaiJingLong** [comment]
0.3.4 版本修复了这个问题.
