### ISSUE TITLE
[Need help]如何生成视频封面

### ISSUE THREAD

**Issue by artcool** [CaiJingLong/flutter_ijkplayer#140]
** 简单描述 **
视频刚刚加载出来的时候是黑屏的，我想截取视频中的某一帧作为封面，请问应该怎么实现啊？有api提供嘛？

** 辅助信息 **

添加一些截图/设计图以便于可以让别人理解你遇到的问题

**Comment by CaiJingLong** [comment]
目前没有提供这样的api. 
一般这种需求,如果是自己的资源是会让上传者添加图片的. 也就是通过接口从自己的服务器端获取.
因为很多视频的首帧可能是黑屏或者不太适合作为视频封面.

**Comment by artcool** [comment]
好的，我明白了。谢谢！

**Comment by GanZhiXiong** [comment]
@CaiJingLong   
我觉得有必要添加封面这样的功能，因为有些场景如播放小视频（类似抖音的小视频）。
**我觉得可以这样实现：自动静音播放一秒，然后暂停，这样还可以显示视频底部栏（进度和全屏按钮）**
