### ISSUE TITLE
[Need help]获取播流出错时 , 如何更改错误提醒?

### ISSUE THREAD

**Issue by 718087538** [CaiJingLong/flutter_ijkplayer#141]
** 简单描述 **
简单描述你遇到的问题
我并不是24小时推流, 未推流时打开播放器会报  "I/O error",
请问我该怎么做,才能把这句错误提醒换成其他的,如"暂时未开播".
** 辅助信息 **

添加一些截图/设计图以便于可以让别人理解你遇到的问题

![image](https://user-images.githubusercontent.com/40202702/66632319-be829d00-ec3a-11e9-9ddd-2113d8ca5113.png)

**Comment by CaiJingLong** [comment]
据我所知, 这个IO/ error 不是这个库的默认界面
---

如果是这个库的功能, 请使用 [根据当前状态构建一个 widget](https://github.com/CaiJingLong/flutter_ijkplayer#%E6%A0%B9%E6%8D%AE%E5%BD%93%E5%89%8D%E7%8A%B6%E6%80%81%E6%9E%84%E5%BB%BA%E4%B8%80%E4%B8%AA-widget) 章节的方案
