### ISSUE TITLE
[Need help] 看视频过程中,android手机会自动息屏,锁屏,怎么破?

### ISSUE THREAD

**Issue by 718087538** [CaiJingLong/flutter_ijkplayer#142]
** 简单描述 **
简单描述你遇到的问题
看视频过程中,手机会自动熄屏, 如何防止息屏?

**Comment by befovy** [comment]
自行控制保持屏幕常亮，可能去玩其他的flutter 插件


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by 718087538** [comment]
> 自行控制保持屏幕常亮，可能需要其他的flutter 插件
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

感觉好多人都会碰到这种问题, 找了好久并没有什么实现方案,老哥有推荐吗??

**Comment by CaiJingLong** [comment]
这个插件看api可以实现, 但我没有真实使用:
https://pub.dev/packages/screen

**Comment by CaiJingLong** [comment]
因为有了对应的插件, 这个功能还是暂时不内置于库内, 如果未来我改变了主意, 我会在库内实现它.

**Comment by befovy** [comment]
@718087538 自己动手，丰衣足食


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by 718087538** [comment]
> 这个插件看api可以实现, 但我没有真实使用:
> https://pub.dev/packages/screen

万分感谢, 万分感谢,解决了  o(^▽^)o   o(^▽^)o

**Comment by 718087538** [comment]
因为

> @718087538 自己动手，丰衣足食
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

使用这个包可以解决,https://pub.dev/packages/screen
我不是专业的移动开发,所以不开会,但还是感谢你的回答. o(^▽^)o
