### ISSUE TITLE
[Bug]release下打开播放器闪退

### ISSUE THREAD

**Issue by yourlin** [CaiJingLong/flutter_ijkplayer#143]
**描述一下你遇到的 bug**
描述一下你的 bug
debug下正常，release下打开视频闪退。
**重现 bug**
测试过OPPO，华为手机，都是这个情况
debug下正常，release下打开视频闪退。

**日志**
因为无法debug，所以没有日志。
目测判断是运行 .network(.......)的时候闪退。

**flutter 版本**

```bash
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.9.1+hotfix.4, on Microsoft Windows [Version 10.0.18362.418], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Ultimate Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.39.1)
[√] Connected device (1 available)

! Doctor found issues in 1 category.

```

**插件版本**
dart: 191.8580
flutter: 40.2.2

dependencies
  flutter_ijkplayer: ^0.3.4

**截图**

**Comment by yourlin** [comment]
怎么查看release日志？

**Comment by befovy** [comment]
@yourlin 和 debug 是一样的呀

**Comment by CaiJingLong** [comment]
无日志无法定位问题
你可以尝试添加一些crash的捕捉框架来捕获错误, 来定位具体的出错原因

**Comment by CaiJingLong** [comment]
只能猜测可能是混淆的问题 因为release和debug的最大差别就在这部分  但这个插件本身没有需要额外混淆的部分
你可以搜索一下 bilibili/IjkPlayer 相关的混淆配置

**Comment by CaiJingLong** [comment]
另外一个可能的原因来自于缺少 flutter 的 so 库.
可以使用android studio 查看 apk 文件内的 so 库是否有所缺失.

我会暂时关闭这个问题, 如果后续可以提供日志或有效帮助定位的方式, 你可以重新打开它.
