### ISSUE TITLE
[Bug] IjkplayerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

### ISSUE THREAD

**Issue by YourksChan** [CaiJingLong/flutter_ijkplayer#144]
Flutter 1.10.15-pre.186 • channel master • https://github.com/flutter/flutter.git
Framework • revision 1c535de7e0 (2 days ago) • 2019-10-18 16:40:42 -0700
Engine • revision 8aefcd8575
Tools • Dart 2.6.0 (build 2.6.0-dev.8.0 a61c775db8)

 Flutter (Channel master, v1.10.15-pre.186, on Mac OS X 10.15 19A602, locale zh-Hans-HK)

出现以下问题：

Running "flutter pub get" in app...                               208.6s (!)
Couldn't read file LocalFile: '/Users/xxx/.pub-cache/git/flutter_ijkplayer-315a7693582ed7bf87f3094b15efe0e0751adf4d/android/src/main/kotlin/top/kikt/ijkplayer/IjkplayerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
Process finished with exit code 1

**Comment by YourksChan** [comment]
Running "flutter pub get" in app...                                67.8s
Couldn't read file LocalFile: '/Users/xxx/.pub-cache/hosted/pub.dartlang.org/flutter_ijkplayer-0.2.8+1/android/src/main/kotlin/top/kikt/ijkplayer/IjkplayerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
Process finished with exit code 1

**Comment by randomjoho** [comment]
可以先运行切换到稳定版 flutter channel stable 
等大佬解决

**Comment by CaiJingLong** [comment]
The plugin latest version is 0.3.4.

**Comment by YourksChan** [comment]
> 可以先运行切换到稳定版 flutter channel stable
> 等大佬解决

切换回稳定版本已正常使用，感谢

**Comment by CaiJingLong** [comment]
@YourksChan 
我看原因是由于插件文件没读取到
据我所知 这个问题是由于 pub 的 git 体系依赖的问题造成的
解决方案就是删除这个 `/Users/xxx/.pub-cache/git/flutter_ijkplayer-315a7693582ed7bf87f3094b15efe0e0751adf4d/` 文件夹

然后重新`$ flutter pub get` 一下

**Comment by CaiJingLong** [comment]
而你的 PR 事实上是新创建了一个新的 commit 造成了 pubspec.yaml 中的ref不同 从而使用了一个新的flutter_ijkplayer-ref 文件夹来作为依赖的目标

理论上来说, 你随便添加一个空格, 然后commit+push一下, pub 的 git 依赖也会重新生成一个文件夹, 造成你所谓的"bug"被修复的假象

**Comment by YourksChan** [comment]
Couldn't read file LocalFile: '/Users/yourks/.pub-cache/hosted/pub.flutter-io.cn/flutter_ijkplayer-0.3.4/android/src/main/kotlin/top/kikt/ijkplayer/IjkplayerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

**Comment by YourksChan** [comment]
> 而你的 PR 事实上是新创建了一个新的 commit 造成了 pubspec.yaml 中的ref不同 从而使用了一个新的flutter_ijkplayer-ref 文件夹来作为依赖的目标
> 
> 理论上来说, 你随便添加一个空格, 然后commit+push一下, pub 的 git 依赖也会重新生成一个文件夹, 造成你所谓的"bug"被修复的假象
> 
> 插件的文件夹放在kotlin中是一个规范代码的方案, 但并不是真实解决这个问题的方案, 望知悉.

Couldn't read file LocalFile: '/Users/yourks/.pub-cache/hosted/pub.flutter-io.cn/flutter_ijkplayer-0.3.4/android/src/main/kotlin/top/kikt/ijkplayer/IjkplayerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.
