### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by 15587879187** [CaiJingLong/flutter_ijkplayer#145]
**描述一下你遇到的 bug**
描述一下你的 bug
iOS打包中出现报错
ld: warning: ignoring file /Users/liutao/Desktop/归档/ios_miao_go/miao_go/ios/Pods/FlutterIJK/IJKMediaFramework.framework/IJKMediaFramework, missing required architecture armv7 in file /Users/liutao/Desktop/归档/ios_miao_go/miao_go/ios/Pods/FlutterIJK/IJKMediaFramework.framework/IJKMediaFramework (3 slices)
Undefined symbols for architecture armv7:
  "_IJKMPMoviePlayerVideoRotationRotateUserInfoKey", referenced from:
      -[CoolIjkNotifyChannel movieRotationChange:] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
  "_IJKMPMoviePlayerVideoRotationNotification", referenced from:
      -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
  "_IJKMPMoviePlayerPlaybackStateDidChangeNotification", referenced from:
      -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
  "_IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
      -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
  "_IJKMPMoviePlayerPlaybackDidFinishReasonUserInfoKey", referenced from:
      -[CoolIjkNotifyChannel moviePlayBackFinish:] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
  "_IJKMPMoviePlayerPlaybackDidFinishNotification", referenced from:
      -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
  "_IJKMPMoviePlayerLoadStateDidChangeNotification", referenced from:
      -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
  "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
      objc-class-ref in libflutter_ijkplayer.a(CoolFlutterIJK.o)
  "_OBJC_CLASS_$_IJKFFOptions", referenced from:
      objc-class-ref in libflutter_ijkplayer.a(CoolFlutterIJK.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
**重现 bug**

通过什么样的步骤可以重现:

**日志**

```

```

**flutter 版本**
使用 `$ flutter doctor -v` 并粘贴详细的信息到这里,如果是特定机型的 bug,请包含设备信息
1.7
```bash

```

**插件版本**

**截图**
如果有,请截图
![image](https://user-images.githubusercontent.com/38445471/67256659-df5cb500-f4ba-11e9-805a-7a0e0ac9fb5d.png)

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_ijkplayer/issues/22#issuecomment-481976222
