### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by kindao1** [CaiJingLong/flutter_ijkplayer#148]
1、不能播放WMV格式视频 
2、请求完成循环播放播放列表的的功能
void load() async{
      await
      controller.setAssetDataSource('images/5.mp4',autoPlay: true);//播放Mp4 正常
      //controller.setAssetDataSource('images/welcomeguide.wmv',autoPlay: true); 不能播放WMV格式的视频 
    }
    IjkMediaController controller = IjkMediaController();
    Widget buildIjkPlayer() {
      load();
      return Container(
        height: 300, // 这里随意
        padding: EdgeInsets.all(10),
        child: IjkPlayer(
          mediaController: controller,
        ),
      );
    }

**Comment by CaiJingLong** [comment]
1. wmv
wmv在当前时代不属于很常见的解码器, 这个库默认关闭了所有的解码器, 在这个基础上只开启了最常见的一些解码器, 强烈建议根据自己的项目进行ffmpeg剪裁, 可以有效降低大小

[自定义编译](https://github.com/caijinglong/flutter_ijkplayer#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BC%96%E8%AF%91%E5%92%8C%E5%8E%9F%E7%94%9F%E9%83%A8%E5%88%86%E6%BA%90%E7%A0%81)看这里

一个公开的库不会也不可能把所有编解码器放进去

---

2. 循环的功能可以考虑加入, 目前你可以用[监听播放完毕的回调](https://github.com/CaiJingLong/flutter_ijkplayer#%E8%B5%84%E6%BA%90%E7%9B%91%E5%90%AC
)来解决

**Comment by CaiJingLong** [comment]
另外 不同的问题应该单独开issue ,而不应该放在同一个内
