### ISSUE TITLE
[Need help] 关于 GSYVideoPlayer 版本冲突问题

### ISSUE THREAD

**Issue by mcxinyu** [CaiJingLong/flutter_ijkplayer#149]
请问你使用的 GSYVideoPlayer 是那个版本？我原生项目也使用了该库，嵌入的时候出现版本冲突。

**Comment by CaiJingLong** [comment]
没有使用这个库

**Comment by befovy** [comment]
@mcxinyu  是不是因为都用了 ijkplayer， 符号冲突了，而不是版本冲突？

**Comment by mcxinyu** [comment]
我不知道so文件有没有版本？有的话能不能告诉我git对应的版本号，这样我可以使用对应版本的gsy，复用你的so文件。

**Comment by befovy** [comment]
都是经过修改的 ijkpalyer， 不能简单共用同一个动态库，得你自己修改  native 代码了。

**Comment by mcxinyu** [comment]
意思是说你的so跟gsy的还不一样咯？那就很难受了，so不可能放两份的。

**Comment by CaiJingLong** [comment]
ijkplayer的源码有所修改 so不可能一样
android部分修改还好, 应该可直接兼容其他的ijkplayer库, 只要clone GSY的源码, 直接引用这个库就可以

ios部分连渲染的逻辑都有修改, 原生的UIView控件不保证可显示图像
