### ISSUE TITLE
Why IOS Volume Controller not showing..?

### ISSUE THREAD

**Issue by cadinz** [CaiJingLong/flutter_ijkplayer#150]
Plz .. help for me

**Comment by CaiJingLong** [comment]
I don't know what you mean?
Provide a screenshot / video to help me.

**Comment by cadinz** [comment]
![B48A5221-06B2-4B18-8032-5159B0C763AD](https://user-images.githubusercontent.com/16585700/68478143-922a6280-0272-11ea-815c-395041a6f848.jpeg)
 This controller is not showing.. when using ijkplayer

**Comment by CaiJingLong** [comment]
The default UI for this system is hidden in the library.
If you need to display it, you may need to wait for future versions I add configuration options to fix.

Or fork project, modify the project ios source implementation, use git dependency.

https://github.com/CaiJingLong/flutter_ijkplayer/blob/7eb1d802ab9928be954f6414b8b16ec815e48807/ios/Classes/IjkplayerPlugin.m#L267-L269

Commenting or deleting these three lines of code should work.

**Comment by cadinz** [comment]
Thanks :) have a nice day!!
