### ISSUE TITLE
[Need help] How can play rmvb format.

### ISSUE THREAD

**Issue by panlin-go** [CaiJingLong/flutter_ijkplayer#153]
** 简单描述 **
我在使用 flutter_ijkplayer时网络播放mp4格式时可以支持的，但是播放rmvb格式的时候，播不出来，请问这个问题应该怎么处理，我需要去那里配置这个编解码格式？

**Comment by panlin-go** [comment]
播放的时候，播放器上面是感叹号。

**Comment by CaiJingLong** [comment]
查看[自定义编译文档](https://github.com/CaiJingLong/flutter_ijkplayer/blob/master/compile-cn.md)

**Comment by CaiJingLong** [comment]
rmvb 在mp4封装,h264+aac一统天下的今天并不是热门格式, 所以并没有添加默认支持.
请参考自定义编译文档,  自定义 ffmpeg 的编解码器及支持的封装格式, 根据自己的实际业务需求来添加或删除不需要的部分.
