### ISSUE TITLE
[Need help] 如何启动就进入全屏？

### ISSUE THREAD

**Issue by panlin-go** [CaiJingLong/flutter_ijkplayer#154]
** 简单描述 **
简单描述你遇到的问题

** 辅助信息 **

如何启动就进入全屏？ 找不到入口，help 大神。

**Comment by CaiJingLong** [comment]
并没有提供简单调用的方案

**Comment by CaiJingLong** [comment]
我可以在下版本加入这个功能

**Comment by panlin-go** [comment]
我先简单的 进去直接 IjkManager.setLandScape();  dispose()的时候 IjkManager.setPortrait(); 将就用，但是这个页面切换的动画不好看。

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_ijkplayer/blob/ee623dd65ead8cf50051f716cca3af62b895de09/example/lib/page/auto_full_screen.dart#L22-L26

**Comment by CaiJingLong** [comment]
在下版本发布后, 这个功能将可用.

**Comment by panlin-go** [comment]
好的， 太感谢了 大神。

**Comment by CaiJingLong** [comment]
OK, you can use 0.3.5.

**Comment by panlin-go** [comment]
谢谢。我试试
