### ISSUE TITLE
flutter_ijkplayer 依赖不下来

### ISSUE THREAD

**Issue by lanzhu1993** [CaiJingLong/flutter_ijkplayer#158]
**Describe the bug**
Couldn't read file LocalFile: '/Users/lanzhu/.pub-cache/hosted/pub.flutter-io.cn/flutter_ijkplayer-0.3.5/android/src/main/kotlin/top/kikt/ijkplayer/IjkplayerPlugin.kt' even though it exists. Please verify that this file has read permission and try again.

**Flutter version**
Flutter 1.12.3-pre.49 • channel master • https://github.com/flutter/flutter.git
Framework • revision 21e6fe1ddf (10 小时前) • 2019-11-17 23:39:51 -0500
Engine • revision 3261324fab
Tools • Dart 2.7.0

**Plugin version**
  flutter_ijkplayer: ^0.3.5

**Comment by SunLongbri** [comment]
我也遇到这个问题

**Comment by SunLongbri** [comment]
我对比了路径，在main中没有kotlin文件夹

**Comment by CaiJingLong** [comment]
你们直接运行example代码也会有同样的问题吗

**Comment by CaiJingLong** [comment]
另外 请提供一下更加完整的 flutter 环境

使用 `flutter doctor -v`输出
我尽量使用完全相同的环境尝试一下

请提供一下更加完整的android环境信息 
包含: compile 的android sdk版本 ,target 版本, min sdk版本号, kotlin版本, classpath版本号, build tool版本号, gradle插件版本, gradle版本(gradle wrapper版本号)

**Comment by SunLongbri** [comment]
我觉得是mac电脑的原因吧，用Windows电脑比较正常。它报了这样的一个错误：Couldn't read file LocalFile:
'/Users/morimatsu_mac_2015/Downloads/flutter/.pub-cache/hosted/pub.flutter-io.cn/flutter_ijkplayer-0.3.5/android/src/main/kotlin/top/kikt/ijkplayer/IjkplayerPlugin.kt' even though it exists.
Please verify that this file has read permission and try again.

而Windows和mac下载的包中都没有这个文件夹。

我的环境：

heaven-2:learning_plus morimatsu_mac_2015$ flutter doctor -v
[✓] Flutter (Channel dev, v1.12.2, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.12.2 at /Users/morimatsu_mac_2015/Downloads/flutter
    • Framework revision 6de6267942 (5 days ago), 2019-11-13 14:37:20 -0800
    • Engine revision b358dc58fb
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/morimatsu_mac_2015/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = /Users/morimatsu_mac_2015/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.3

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

**Comment by CaiJingLong** [comment]
因为kotlin文件放在java目录里是很常见的情况, 本项目也是如此
所以这个文件确实不存在, 所以我怀疑是编译工具链的问题,这也是为什么我觉得我需要完整android工具链来排查问题的原因

**Comment by SunLongbri** [comment]
那这个问题有没有比较好的解决方法呢？毕竟我感觉这个插件还是很好的。我需不需要将kotlin从java目录中移到main目录下呢？

**Comment by CaiJingLong** [comment]
似乎这并不是一个个例, 我觉得问题很有可能是flutter tool的问题, 但官方并没有很合适的解决方案 flutter/flutter#42923
但最难解决的原因是我的mac无法模拟这个情况, 如果可以, 你可能需要提供一个完整的flutter工程来帮助我复现这个问题, 让我能从根源上来解决它.

**Comment by SunLongbri** [comment]
非常乐意效劳：这个是我的代码，就是拉取插件出现问题的项目工程：
https://github.com/SunLongbri/learning_plus

**Comment by CaiJingLong** [comment]
stable分支没有这个问题
我在 master 分支上可以复现这个问题
猜测应该是 flutter sdk的问题

**Comment by SunLongbri** [comment]
好的，我转到stable分支试试。

**Comment by SunLongbri** [comment]
我之前用的是 dev 分支

**Comment by CaiJingLong** [comment]
报错的来源是这里. 具体是哪个commit提交的我没追, 现在只会在java文件夹里找java, kotlin文件夹里找kt, 而这个过程不会读取gradle的src配置, 属于写死的约定.

https://github.com/flutter/flutter/blob/cb614d13394125ea8dcdc1ebcb7f03da22f59fc2/packages/flutter_tools/lib/src/platform_plugins.dart#L97-L106

**Comment by CaiJingLong** [comment]
我会单独先提交一下小版本来修复这个问题.

**Comment by SunLongbri** [comment]
厉害厉害，我感觉你是大佬呀。

**Comment by SunLongbri** [comment]
好羡慕你们，这么厉害。

**Comment by CaiJingLong** [comment]
New version 0.3.5+1.

**Comment by lanzhu1993** [comment]
感谢，感谢
