### ISSUE TITLE
关于flutter_ijkplayer 插件

### ISSUE THREAD

**Issue by 0-php** [CaiJingLong/flutter_ijkplayer#16]
请问 flutter_ijkplayer 有没有办法监听 播放器事件比如VideoPlayer 插件
能不能支持 addListener 事件
_videoPlayerController1 = VideoPlayerController.network(widget.url)..addListener(() {
      final bool isPlaying = _videoPlayerController1.value.isPlaying;
      if (isPlaying != _isPlaying) {
        setState(() { _isPlaying = isPlaying; });
      }
    })..initialize().then((_) {
      setState(() {});
    })

**Comment by CaiJingLong** [comment]
你是指的这个?
https://github.com/CaiJingLong/flutter_ijkplayer#%E8%B5%84%E6%BA%90%E7%9B%91%E5%90%AC

**Comment by 0-php** [comment]
@CaiJingLong 
`
// 播放状态的监听,true为正在播放,false为暂停
Stream<bool> playingStream = controller.playingStream;
`
这个好像是的 但是怎么调用呢可以实现主动通知吗？

**Comment by CaiJingLong** [comment]
Stream类的用法可以参考dart/flutter的文档, 这个类是dart sdk的一部分.

或者参考示例代码
