### ISSUE TITLE
[Bug] 播放视频出现绿边，并且高度超出父控件范围

### ISSUE THREAD

**Issue by mcxinyu** [CaiJingLong/flutter_ijkplayer#162]
我不知道能不能归类到 bug 里面。
播放视频时出现绿边，并且高度超出父控件范围，没有报告任何错误。

http://image2.njf2016.com/lmOSs_B237iJaPmulEYONaqymdTU

次视频在其他（小程序/浏览器/PC视频播放器）地方显示正常。

**Comment by mcxinyu** [comment]
以下是用本项目的代码替换视频链接的效果，手机是三星s10+

![Screenshot_20191120-170753](https://user-images.githubusercontent.com/9566116/69225000-7733e880-0bb8-11ea-8013-bc2afe9872b0.jpg)
![Screenshot_20191120-170759](https://user-images.githubusercontent.com/9566116/69225003-79964280-0bb8-11ea-9448-aed173a6426e.jpg)

**Comment by befovy** [comment]
@mcxinyu 
可以试试用 原生 android ijkplayer 播放一下这个文件，看看绿边问题。我试了是没有的。
同时 https://github.com/befovy/fijkplayer 这个插件我也试了，没有绿边。

@CaiJingLong  这个问题我不是很理解了。android 视频对接到 flutter 中，是直接使用 surface 进行的，用的不是裸视频数据。应该不会产生这个问题的呀。

**Comment by mcxinyu** [comment]
我使用官方的videoplayer也有这个问题，而且是在一些手机和一些视频才会，大部分出现的是高宽比较大的视频，我觉得出现问题可能是：视频的高度（texture）超出了父控件导致的（flutter bug）

**Comment by befovy** [comment]
我是指你用  https://github.com/bilibili/ijkplayer 编译的 android app 试一下，不是说 flutter 中的 videoplayer。 @mcxinyu

**Comment by CaiJingLong** [comment]
> @mcxinyu
> 可以试试用 原生 android ijkplayer 播放一下这个文件，看看绿边问题。我试了是没有的。
> 同时 https://github.com/befovy/fijkplayer 这个插件我也试了，没有绿边。
> 
> @CaiJingLong 这个问题我不是很理解了。android 视频对接到 flutter 中，是直接使用 surface 进行的，用的不是裸视频数据。应该不会产生这个问题的呀。

这个我也不是很理解, 安卓部分的源码对于纹理部分并没有任何改动, 纹理渲染部分用的是 bilibili 

也许问题确实来源于flutter sdk
但 flutter engine 关于纹理渲染部分的核心渲染代码似乎很长时间没有改动, 所以我确实不知道问题出在哪里

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/69298313-6a5ed580-0c48-11ea-9c22-e5bd5feee605.png)

@mcxinyu 
这个是我使用本仓库的example中的network page显示的, 并没有绿色边的出现

**Comment by befovy** [comment]
所以是和 @mcxinyu 说的特定手机有关？

**Comment by CaiJingLong** [comment]
@befovy 
因为按照描述 video_player 也有同样的问题, 也就是说这个问题很可能来自于 flutter 层, 当然也有可能是硬解码的问题
因为讲道理来说 exo player 和 ijkplayer 的核心渲染都在同一个地方出的问题的概率不大

**Comment by mcxinyu** [comment]
@befovy @CaiJingLong 感谢两位了，其实[昨天](https://github.com/CaiJingLong/flutter_ijkplayer/issues/162#issuecomment-555928025)已经可以确定是 flutter sdk 的问题了，因为 videoplayer 也会出现这种问题（只是大部分手机和视频没有触发这个bug，例如你们手中的设备）。我会将这个问题反馈给flutter去修复，有时间我也会去尝试看能不能找出根本问题。感谢。

**Comment by chinacode** [comment]
> @befovy @CaiJingLong 感谢两位了，其实[昨天](https://github.com/CaiJingLong/flutter_ijkplayer/issues/162#issuecomment-555928025)已经可以确定是 flutter sdk 的问题了，因为 videoplayer 也会出现这种问题（只是大部分手机和视频没有触发这个bug，例如你们手中的设备）。我会将这个问题反馈给flutter去修复，有时间我也会去尝试看能不能找出根本问题。感谢。

这不是flutter sdk 的问题吧，应该也视频倍数问题

**Comment by mcxinyu** [comment]
视频倍数啥意思呢？

**Comment by pickView** [comment]
我也复现了该bug，但是直接使用的video_player,，有解决方案吗

**Comment by nodevue** [comment]
请问这个问题后面有跟踪修复么？我这边也遇到了同样的情况
