### ISSUE TITLE
[Need help]

### ISSUE THREAD

**Issue by jcliang1212** [CaiJingLong/flutter_ijkplayer#173]
Describe your needs
麻烦问一下，你这个库集成的openssl是哪个版本号？谢谢

If possible, add prototypes / designs and other supporting documents to help others understand your needs.

**Comment by CaiJingLong** [comment]
和 bilibili/ijkplayer 完全相同, 具体版本号没看过
实际的指向项目应该是这个 https://github.com/Bilibili/openssl

**Comment by jcliang1212** [comment]
> 和 bilibili/ijkplayer 完全相同, 具体版本号没看过
> 实际的指向项目应该是这个 https://github.com/Bilibili/openssl

好的，谢谢
