### ISSUE TITLE
[Need help]android原生部分已经集成了GSYVideoPlayer，编译冲突

### ISSUE THREAD

**Issue by Wanchen7** [CaiJingLong/flutter_ijkplayer#179]
** 简单描述 **
安卓原生部分集成了GSYVideoPlayer，flutter端集成这个库后以aar形式集成到app中编译报错。这个需要如何处理？

** 辅助信息 **
`Duplicate class tv.danmaku.ijk.media.player.IMediaPlayer$OnVideoSizeChangedListener found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.ISurfaceTextureHolder found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.ISurfaceTextureHost found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkLibLoader found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaCodecInfo found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaMeta found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaMeta$IjkStreamMeta found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaPlayer found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaPlayer$1 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaPlayer$DefaultMediaCodecSelector found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaPlayer$EventHandler found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaPlayer$OnControlMessageListener found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaPlayer$OnMediaCodecSelectListener found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkMediaPlayer$OnNativeInvokeListener found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.IjkTimedText found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaInfo found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy$1 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy$2 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy$3 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy$4 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy$5 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy$6 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy$7 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.MediaPlayerProxy$8 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.TextureMediaPlayer found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.annotations.AccessedByNative found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.annotations.CalledByNative found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.exceptions.IjkMediaException found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.ffmpeg.FFmpegApi found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.AndroidMediaFormat found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.AndroidTrackInfo found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IAndroidIO found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IMediaDataSource found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IMediaFormat found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.ITrackInfo found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$1 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$2 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$3 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$4 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$5 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$6 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$7 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$8 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$9 found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkMediaFormat$Formatter found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.misc.IjkTrackInfo found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.pragma.DebugLog found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)
Duplicate class tv.danmaku.ijk.media.player.pragma.Pragma found in modules classes.jar (top.kikt.ijkplayer:flutter_ijkplayer_debug:1.0) and classes.jar (tv.danmaku.ijk.media:ijkplayer-java:0.8.8)`

**Comment by CaiJingLong** [comment]
java文件重复引入了
这个问题无法解决
即使java的类可以不重复引入, so库也会重复引用.

**Comment by Wanchen7** [comment]
sad  我只能先不用此库了

**Comment by zjmok** [comment]
兄弟最后用了哪个播放器库
