### ISSUE TITLE
安卓9.0 无法安装会出现闪退的情况

### ISSUE THREAD

**Issue by 0-php** [CaiJingLong/flutter_ijkplayer#18]
**描述一下你遇到的bug**
描述一下你的bug

**重现bug**
安卓9.0 无法安装会出现闪退的情况
用手机和 模拟器都是一样的结果 安卓7.0正常

**Comment by CaiJingLong** [comment]
你可以尝试贴一下错误信息吗
另外: 你运行的是example吗,还是使用pub依赖到自己的项目中
我这里模拟器和真机9.0都是正常的

**Comment by 0-php** [comment]
➜  example flutter run --release                  
Initializing gradle...                                              1.3s
Resolving dependencies...                                           1.7s
Launching lib/main.dart on Google Pixel 1 in release mode...
Profile and release builds are only supported on ARM targets.
Error running application on Google Pixel 1.

**Comment by CaiJingLong** [comment]
release版本不支持x86 cpu,但这个不是插件的原因
而是flutter的原因 查看flutter/flutter#9253

**Comment by CaiJingLong** [comment]
你可以创建并运行 flutter create first_example
你会得到同样的信息

**Comment by 0-php** [comment]
@CaiJingLong  我经过测试其实不是 安卓9.0会崩溃而是因为在
~/project1/android/build.gradle 中加入了
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

这段代码的话 我通过正常的发包 flutter build apk --release 然后下载到手机上后会出现 闪退的情况 不止安卓9.0我的安卓7.0也会出现闪退
不是做安卓出来的遇到这个问题很痛苦 有没有办法解决？
今天试了很多办法都不行
