### ISSUE TITLE
看了一下ijk的源码，是支持arm7的，但是这里是不支持吗？如何可以适配呢？ [Need help] 

### ISSUE THREAD

**Issue by aerokwok** [CaiJingLong/flutter_ijkplayer#185]
Describe your needs

If possible, add prototypes / designs and other supporting documents to help others understand your needs.

**Comment by CaiJingLong** [comment]
不是IjkPlayer不支持armv7 而是xcode不支持 
以前解释过: https://github.com/CaiJingLong/flutter_ijkplayer/issues/22#issuecomment-496411498

**Comment by aerokwok** [comment]
那这块是适配不了了？




在2020年01月13日 17:13，Caijinglong 写道：

不是IjkPlayer不支持armv7 而是xcode不支持
以前解释过: #22 (comment)

**Comment by CaiJingLong** [comment]
如果一定需要 可以自己下载xcode7 然后编译出支持armv7的 IjkPlayer的framework
然后替换进自己的工程.

但个人认为没有任何意义

**Comment by aerokwok** [comment]
好的，知道了。谢谢啦




在2020年01月13日 17:20，Caijinglong 写道：

如果一定需要 可以自己下载xcode7 然后编译出支持armv7的 IjkPlayer的framework
然后替换进自己的工程.

但个人认为没有任何意义
