### ISSUE TITLE
seekTo 没用

### ISSUE THREAD

**Issue by leetomlee123** [CaiJingLong/flutter_ijkplayer#189]
**描述一下你遇到的 bug**
描述一下你的 bug

**重现 bug**

通过什么样的步骤可以重现:

**日志**

```

```

**flutter 版本**
使用 `$ flutter doctor -v` 并粘贴详细的信息到这里,如果是特定机型的 bug,请包含设备信息

```bash

```

**插件版本**

**截图**
如果有,请截图

**Comment by CaiJingLong** [comment]
seekTo 只是对接的官方ijkplayer, 并没有任何修改
如果是直播流是不支持的

**Comment by Maclaon** [comment]
seekTo 确实不起作用的，不知道大家怎么使用的，我设置好链接后，`seekTo(30)`，没啥反应！
