### ISSUE TITLE
[Need help]有办法从一个数据流来播放视频么？

### ISSUE THREAD

**Issue by OhYee** [CaiJingLong/flutter_ijkplayer#19]
** 简单描述 **
有将[flutter-ffmpeg](https://github.com/tanersener/flutter-ffmpeg)处理后的视频流播放出来的方案么?

ffmpeg貌似只能输出成文件或者到一个rtmp服务器上，没有办法做预览功能

** 辅助信息 **

**Comment by CaiJingLong** [comment]
这个问题可能我需要查看一下flutter-ffmpeg这个库的源码
看看ffmpeg的数据有没有办法直接接入ijkplayer中

另外,因为ijkplayer是基于bilibili的原生封装的, 如果bilibili/ijkplayer没有提供这样的数据源对接功能,则无法保证可以对接其他的sdk

**Comment by CaiJingLong** [comment]
这个库中使用的是asset中的二进制执行文件(linux for android), 目前来看没有办法将流对接到ijkplayer中.

以我的技术能力, 我没有看到有实现的可能.
