### ISSUE TITLE
JNI_ERR returned from JNI_OnLoad

### ISSUE THREAD

**Issue by VNAPNIC** [CaiJingLong/flutter_ijkplayer#197]
[IjkOption{category: IjkOptionCategory.player, key: soundtouch, value: 1}, IjkOption{category: IjkOptionCategory.player, key: start-on-prepared, value: 1}]
E/flutter (23303): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/vn.gvntechnology.liveshop.dev-g9uttmqPnPcoDriOwZS6jw==/lib/arm64/libijksdl.so"
E/flutter (23303): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
E/flutter (23303): 	at java.lang.System.loadLibrary(System.java:1669)
E/flutter (23303): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(Unknown Source:0)
E/flutter (23303): 	at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source:18)
E/flutter (23303): 	at f.a.a.e.onMethodCall(Unknown Source:11)
E/flutter (23303): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter (23303): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
E/flutter (23303): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter (23303): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (23303): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter (23303): 	at android.os.Looper.loop(Looper.java:181)
E/flutter (23303): 	at android.app.ActivityThread.main(ActivityThread.java:6981)
E/flutter (23303): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (23303): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/flutter (23303): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
E/flutter (23303):

**Comment by befovy** [comment]
@CaiJingLong 在库中使用 consumerProguardFiles  可以彻底解决这类混淆问题

**Comment by CaiJingLong** [comment]
@befovy I think I can add it in plugin.  😄

**Comment by CaiJingLong** [comment]
@VNAPNIC 
It is problem of `Proguard`.

Try to add next code to your proguard file.
```
-keep class tv.danmaku.ijk.media.player.** {
    *;
}
```
