### ISSUE TITLE
IOS真机播放没有图像

### ISSUE THREAD

**Issue by jendy2012** [CaiJingLong/flutter_ijkplayer#2]
IOS真机播放没有图像，偶尔会有图像，但是不能拖动，一拖动就会卡在那里。有的时候，进去就是黑屏的。

**Comment by CaiJingLong** [comment]
本地还是网络
使用的版本号是多少

**Comment by jendy2012** [comment]
本地视频播放正常。主要是网络视频不能播放，版本用的是你最近发布的版本。0.1.4.
'http://www.sample-videos.com/video123/mp4/720/big_buck_bunny_720p_20mb.mp4',
'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4',
 'https://media.w3.org/2010/05/sintel/trailer.mp4',
'http://img.ksbbs.com/asset/Mon_1703/05cacb4e02f9d9e.mp4',
这几个文件都只有声音没有图像。
代码用的是你的列子代码。

**Comment by CaiJingLong** [comment]
设备机型呢

输出一下完整的 `flutter doctor -v` 吧

**Comment by jendy2012** [comment]
设备机型是iphone x
本地视频完全没有问题。
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/jendy/flutter
    • Framework revision 8661d8aecd (5 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/jendy/android/android-sdk-macosx/
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/jendy/android/android-sdk-macosx/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    ✗ Android license status unknown.

[!] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.1
    ✗ ios-deploy out of date (1.9.4 is required). To upgrade with Brew:
        brew upgrade ios-deploy
    • CocoaPods version 1.7.0.beta.2

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 31.3.4
    • Dart plugin version 183.4886.3

[✓] VS Code (version 1.32.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.24.0

**Comment by CaiJingLong** [comment]
在播放网络视频前先清空一下日志
然后等待一会儿 把日志发送一份相对完整的到这里来

----
我估计可能是ffmpeg的http协议有问题,我这几天重新编译一套库文件再试试
你有rtmp的网络源吗,也可以尝试一下

**Comment by jendy2012** [comment]
好的。flutter: ijkplayer: onTextChange
flutter: ijkplayer: id = 1 net uri = http://img.ksbbs.com/asset/Mon_1703/05cacb4e02f9d9e.mp4
OK setup GL
flutter: set data source success
FFP_MSG_OPEN_INPUT:
FFP_MSG_FIND_STREAM_INFO:
FFP_MSG_AUDIO_RENDERING_START:
FFP_MSG_VIDEO_DECODER_OPEN: false
FFP_MSG_COMPONENT_OPEN:
FFP_MSG_VIDEO_ROTATION_CHANGED:
rotate arg1 = 0
FFP_MSG_VIDEO_SIZE_CHANGED: 600, 338
FFP_MSG_SAR_CHANGED: 676, 675
FFP_MSG_PREPARED:
fps in meta 25.000000
flutter: ijkplayer: onRotateChanged , info = {"isPlaying":true,"degree":0,"currentPosition":0.0,"width":0,"height":0,"duration":244.203}
FFP_MSG_VIDEO_SIZE_CHANGED: 600, 338
FFP_MSG_VIDEO_DECODED_START:
FFP_MSG_VIDEO_SIZE_CHANGED: 600, 338
FFP_MSG_VIDEO_SIZE_CHANGED: 600, 338
FFP_MSG_VIDEO_RENDERING_START:
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":0.0,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":0.0,"width":600,"height":338,"duration":244.203}
FFP_MSG_AUDIO_DECODED_START:
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":0.172,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":0.58,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":0.971,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":1.37,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":1.768,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":2.171,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":2.568,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":2.967,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":3.372,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":3.769,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":4.172,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":4.571,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":4.968,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":5.371,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":5.771,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":6.168,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":6.571,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":6.984,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":7.371,"width":600,"height":338,"duration":244.203}
flutter: ijkplayer: will refresh info
flutter: ijkplayer: info = {"isPlaying":true,"degree":0,"currentPosition":7.858,"width":600,"height":338,"duration":244.203}

**Comment by jendy2012** [comment]
你参考一下这个看看
https://github.com/bilibili/ijkplayer/issues/3643

**Comment by CaiJingLong** [comment]
我试一下

**Comment by CaiJingLong** [comment]
我重新编译过iOS库并且上传了pod 

你可以尝试当前的master版本 使用git依赖
```yaml
dependencies:
  flutter_ijkplayer:
    git:
      url: https://github.com/CaiJingLong/flutter_ijkplayer.git
      ref: 77609d1c5069d82b1111bc25f275267f0d895dbc
```

我会在修复一些其他问题后上传新的pub版本

**Comment by CaiJingLong** [comment]
我在昨天上传了新的0.1.5版本
欢迎尝试使用

**Comment by jendy2012** [comment]
![IMG_6257](https://user-images.githubusercontent.com/2418263/54880099-0e0aa280-4e7c-11e9-9ec1-6efdea777e57.PNG)
![IMG_6258](https://user-images.githubusercontent.com/2418263/54880101-0e0aa280-4e7c-11e9-8f52-28df6fedc366.PNG)
0.1.5版本还是一样的。
黑屏的是在线播放的
另外一个是本地文件。

**Comment by jendy2012** [comment]
![IMG_6259](https://user-images.githubusercontent.com/2418263/54880702-b28fe300-4e82-11e9-8782-cb29e7f1c429.PNG)

这个https的可以用。
或者是不是确实是播放文件的解码问题？

**Comment by jendy2012** [comment]
https://media.w3.org/2010/05/sintel/trailer.mp4
http://img.ksbbs.com/asset/Mon_1703/05cacb4e02f9d9e.mp4
http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4
这些都播放不了

**Comment by CaiJingLong** [comment]
我检查过日志
ffmpeg会抛出
FFP_MSG_VIDEO_DECODER_OPEN: false 这样的错误,这应该代表video的解码器无法工作

因为我一直是用可以那个可以打开的文件测试的.. 所以没有出现问题

我单独检查一下这些文件,查看下视频编码方式,再看看怎么样可以解决问题

**Comment by CaiJingLong** [comment]
我把你提供的连接中的文件下载后放入asset,也没有画面

**Comment by CaiJingLong** [comment]
我跟了一下代码,并且做了尝试
这个似乎是flutter引擎的问题..
我将iOS中的黑屏画面的`CVPixelBufferRef` 转为UIImage数据传入Flutter端进行显示,可以得到图片
但是这个数据在flutter转为texture的时候,无法成功渲染

**Comment by CaiJingLong** [comment]
但是使用flutter官方的video_player插件,这个视频是可播放的
所以我现在不知道是视频解码的问题还是官方Texture渲染时的问题

**Comment by jendy2012** [comment]
你看下他这个
https://github.com/An-uking/Flutter_IJKPlayer
他这个是可以播放的。只是功能不完整。

**Comment by CaiJingLong** [comment]
他那个是PlatformView做的

一直说有一个纹理的,然而不开源

**Comment by CaiJingLong** [comment]
修复了这个问题,稍后我会更新0.1.7版本

**Comment by jendy2012** [comment]
OK，测试了。现在一切正常。
感谢。
