### ISSUE TITLE
[Need help] How to play wav file on both android and ios?

### ISSUE THREAD

**Issue by Nyamkhuub** [CaiJingLong/flutter_ijkplayer#205]
Hello developers!
I want to play wav file on application. Here is my code.

```
FloatingActionButton(
        onPressed: () async {
          await controller.setNetworkDataSource(
              'https://mybucket/test_audio.wav',
              autoPlay: true);
          // controller.playOrPause();
        },
        tooltip: 'Play an audio',
        child: Icon(Icons.add),
      ),
    )
```

> E/IJKMEDIA(29714): https://mybucket/test_audio.wav: Invalid data found when processing input

How to solve this problem?

**Comment by CaiJingLong** [comment]
Now, the ffmpeg of flutter_ijkplayer haven't contains wav format, I think you need compile the ijkplayer . And replace so and framework into your project.

The current compilation configuration file is [here](https://gitee.com/kikt/ijkplayer_thrid_party/blob/master/config/module.sh), the specific compilation method can see [this document](https://github.com/CaiJingLong/flutter_ijkplayer/blob/master/compile.md). 

For other questions about compilation can go to [bilibili/ijkplayer](https://github.com/bilibili/ijkplayer)

**Comment by Nyamkhuub** [comment]
Thanks I will try it
