### ISSUE TITLE
[Bug] mix usage of http/https urls of the same domain

### ISSUE THREAD

**Issue by dotcink** [CaiJingLong/flutter_ijkplayer#214]
**描述一下你遇到的 bug**

同一域名下的 http 和 https 链接不能混用。

**重现 bug**

先播放 https 视频，再播放 http 视频（同一域名），后者会失败。

**日志**

```
IJKMEDIA: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_ijkplayer#%E8%87%AA%E5%AE%9A%E4%B9%89-option

**Comment by CaiJingLong** [comment]
你可以在flutter端使用你需要的任何option

**Comment by dotcink** [comment]
明白了，多谢，之前没注意到这个功能
