### ISSUE TITLE
statusWidgetBuilder 如何应用到全屏模式

### ISSUE THREAD

**Issue by batdkuwlh** [CaiJingLong/flutter_ijkplayer#217]
statusWidgetBuilder 如何应用到全屏模式，在全屏时还是默认的处理样式，没有找到相应的方法

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/77716913-27f43d80-701a-11ea-84b9-4ba01b7dbf10.png)

[文档](https://github.com/CaiJingLong/flutter_ijkplayer#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%A7%E5%88%B6%E5%99%A8-ui)看自定义全屏
