### ISSUE TITLE
flutter_ijkplayer 在IOS真机上运行报错

### ISSUE THREAD

**Issue by 0-php** [CaiJingLong/flutter_ijkplayer#22]
**描述一下你遇到的bug**
➜  flutter build ios
Building flutter.sex.com.sex for device (ios-release)...
Automatically signing iOS for device deployment using specified development team in Xcode project: GU9M63AKDT
Running pod install...                                              0.7s
CocoaPods' output:
↳
      Preparing

    Analyzing dependencies

    Inspecting targets to integrate
      Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)

    Finding Podfile changes
      A flutter_ijkplayer
      M Flutter
      - path_provider
      - shared_preferences
      - url_launcher

    Fetching external sources
    -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
    -> Fetching podspec for `flutter_ijkplayer` from `.symlinks/plugins/flutter_ijkplayer/ios`
    -> Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
    -> Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
    -> Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`

    Resolving dependencies of `Podfile`
    [!] Unable to find a specification for `FlutterIJK (~> 0.0.9)` depended upon by `flutter_ijkplayer`

    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:402:in `find_cached_set'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:372:in `specifications_for_dependency'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:177:in `search_for'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:288:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `each'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_by'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:281:in `sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/resolver.rb:123:in `resolve'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:781:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:779:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:88:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
    /Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
    /Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
    /usr/local/bin/pod:22:in `load'
    /usr/local/bin/pod:22:in `<main>'

Error output from CocoaPods:
↳

    [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for
    this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

Error running pod install

2.运行 pos install 
➜  ios pod install
Analyzing dependencies
Fetching podspec for `Flutter` from `.symlinks/flutter/ios-release`
Fetching podspec for `flutter_ijkplayer` from `.symlinks/plugins/flutter_ijkplayer/ios`
Fetching podspec for `path_provider` from `.symlinks/plugins/path_provider/ios`
Fetching podspec for `shared_preferences` from `.symlinks/plugins/shared_preferences/ios`
Fetching podspec for `url_launcher` from `.symlinks/plugins/url_launcher/ios`
[!] Unable to find a specification for `FlutterIJK (~> 0.0.9)` depended upon by `flutter_ijkplayer`

[!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.

说没有FlutterIJK 不知道怎么处理

**Comment by 0-php** [comment]
详细信息

➜   flutter doctor -v 
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/sam/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/sam/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • “sam”的 iPhone • c77a337cc6c9c2b76ce957d6545a5662b2bf604b • ios • iOS 12.1.4

! Doctor found issues in 1 category.

**Comment by 0-php** [comment]
我运行了pod repo update 之后解决了上面的BUG但是出来新的问题
运行：flutter build ios

BUG如下：
Xcode's output:
↳
    ld: warning: ignoring file /Users/sam/sex/ios/Pods/FlutterIJK/IJKMediaFramework.framework/IJKMediaFramework, missing required architecture armv7
    in file /Users/sam/sex/ios/Pods/FlutterIJK/IJKMediaFramework.framework/IJKMediaFramework (3 slices)
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_IJKFFOptions", referenced from:
          objc-class-ref in libflutter_ijkplayer.a(CoolFlutterIJK.o)
      "_IJKMPMoviePlayerVideoRotationRotateUserInfoKey", referenced from:
          -[CoolIjkNotifyChannel movieRotationChange:] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerPlaybackStateDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerVideoRotationNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerPlaybackDidFinishNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
          objc-class-ref in libflutter_ijkplayer.a(CoolFlutterIJK.o)
      "_IJKMPMoviePlayerLoadStateDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by CaiJingLong** [comment]
![image](https://user-images.githubusercontent.com/14145407/55933938-956c5a00-5c61-11e9-98b9-1071508ccb40.png)

**Comment by qq125183592** [comment]
非常感谢，解决了

**Comment by MeDeity** [comment]
为什么不加上armv7的so库包呢?  @CaiJingLong ,我在window电脑上使用codemagic网站协助打IOS包好像没办法进行这样的设置. 提前感谢!

**Comment by CaiJingLong** [comment]
@MeDeity 
从xcode8开始就不支持打出armv7的的库, 因为iOS很早开始就不支持32位机了
而现在已经是XCode10了

远程打包的事情我帮不了你, 你可以咨询下这个打包网站如何配置

**Comment by MeDeity** [comment]
好的,再次感谢

**Comment by JunevaYang** [comment]
图片已经失效了  可不可以更新下
