### ISSUE TITLE
[Need help] 缓冲收到bufferend的状态后仍会卡几秒钟才播放

### ISSUE THREAD

**Issue by xingyuyechen** [CaiJingLong/flutter_ijkplayer#223]
我将整个项目下载下来了，修改了代码，在android端暴露了bufferstart和bufferend的接口在dart端，缓冲时开始缓冲和缓冲结束的状态正常收到了，但是在缓冲结束后画面仍然会卡几秒才会正常播放，像是填满缓冲池后又填了一个缓冲池才播放，请问是什么原因？是ijkplayer要加什么属性吗？

**Comment by CaiJingLong** [comment]
我印象中IjkPlayer的原生也是这么设计的

你可以试试在IjkPlayer的官方example中添加buffer监听, 看看能否印证你的想法

**Comment by xingyuyechen** [comment]
破案了，是enable-accurate-seek属性的问题。IJKMEDIA有报一个accurate-seek的warn，注掉enable-accurate-seek就没有这个问题了。
