### ISSUE TITLE
[Bug] android release后闪退

### ISSUE THREAD

**Issue by chenyifan88** [CaiJingLong/flutter_ijkplayer#227]
**描述一下你遇到的 bug**
编译android release后，引用0.3.5+1 版本的库闪退，debug模式下正常，

**个人判断**
缺少release后的相关so文件，麻烦大佬看看
**重现 bug**

通过什么样的步骤可以重现:

1. 引用0.3.5+1的库，
2. 调用
IjkMediaController _ijkController;
@override
  void initState() {
    // TODO: implement initState
    super.initState();
    var url ='xxx';
    _ijkController = IjkMediaController(autoRotate: false);
    _ijkController.setDataSource(DataSource.network(url), autoPlay: true);
  }
3. 直接编译一个release的apk
**日志**
2020-04-15 22:31:22.291 13061-13061/? E/J4A: J4A_FindClass__catchAll: failed
2020-04-15 22:31:22.291 13061-13061/? E/J4A: J4A_FindClass__asGlobalRef__catchAll: failed: tv/danmaku/ijk/media/player/misc/IMediaDataSource
2020-04-15 22:31:22.293 13061-13061/? E/flutter: [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.test.ijk-9vS28HXnAKGnDqeI08khww==/lib/arm/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1672)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.a(Unknown Source:0)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.b(Unknown Source:18)
        at g.a.a.e.a(Unknown Source:11)
        at e.a.c.a.j$a.a(Unknown Source:17)
        at io.flutter.embedding.engine.e.b.a(Unknown Source:57)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:386)
        at android.os.Looper.loop(Looper.java:175)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
2020-04-15 22:31:22.293 13061-13061/? A/flutter: [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 

```

```

**flutter 版本**
使用 `$ flutter doctor -v` 并粘贴详细的信息到这里,如果是特定机型的 bug,请包含设备信息
[✓] Flutter (Channel stable, v1.12.13+hotfix.7, on Mac OS X 10.15.2 19C57,
    locale zh-Hans-PH)
    • Flutter version 1.12.13+hotfix.7 at /Users/mac/FlutterSDK/flutter
    • Framework revision 9f5ff2306b (3 months ago), 2020-01-26 22:38:26 -0800
    • Engine revision a67792536c
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio
      2.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio 2.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • MAR LX2 • 8RB4C19927001827 • android-arm64 • Android 9 (API 28)

• No issues found!
```bash

```

**插件版本**
0.3.5+1
**截图**
如果有,请截图

**Comment by Maclaon** [comment]
相同的问题出现，提供提示，不确定是不是该问题的原因，日志太多
```
java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.misc.IMediaDataSource" on path: DexPathList
```
[flutter APP crash](https://groups.google.com/forum/#!topic/flutter-dev/0AvZ17FJsS0)给出了答案，可以参考：

> The adb logcat :
System.err: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.misc.IMediaDataSource" on path

> it should be cause by code proguard-rules, i'am tried touch `proguard-rules.pro` on the 'android/app/' path and addition "-keep class tv.danmaku.ijk.media.player.** {*;}" into the file, when i rerty the build "flutter build apk && flutter install " that it is work well.

在`android/app/`下新建`proguard-rules.pro`，成功！
```
-keep class tv.danmaku.ijk.media.player.** {*;}
```

**Comment by CaiJingLong** [comment]
As @Maclaon  said, adding this code is valid.
It has been added by default in the new version of [proguard](https://github.com/CaiJingLong/flutter_ijkplayer/blob/master/android/proguard-rules.pro), but no pub has been uploaded yet.

**Comment by chenyifan88** [comment]
> 相同的问题出现，提供提示，不确定是不是该问题的原因，日志太多
> 
> ```
> java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.misc.IMediaDataSource" on path: DexPathList
> ```
> 
> [flutter APP crash](https://groups.google.com/forum/#!topic/flutter-dev/0AvZ17FJsS0)给出了答案，可以参考：
> 
> > The adb logcat :
> > System.err: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.misc.IMediaDataSource" on path
> 
> > it should be cause by code proguard-rules, i'am tried touch `proguard-rules.pro` on the 'android/app/' path and addition "-keep class tv.danmaku.ijk.media.player.** {*;}" into the file, when i rerty the build "flutter build apk && flutter install " that it is work well.
> 
> 在`android/app/`下新建`proguard-rules.pro`，成功！
> 
> ```
> -keep class tv.danmaku.ijk.media.player.** {*;}
> ```

解决了。确实是我放错了混淆文件位置

**Comment by Seven163** [comment]
> > 相同的问题出现，提供提示，不确定是不是该问题的原因，日志太多
> > ```
> > java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.misc.IMediaDataSource" on path: DexPathList
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [flutter APP crash](https://groups.google.com/forum/#!topic/flutter-dev/0AvZ17FJsS0)给出了答案，可以参考：
> > > The adb logcat :
> > > System.err: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.misc.IMediaDataSource" on path
> > 
> > 
> > > it should be cause by code proguard-rules, i'am tried touch `proguard-rules.pro` on the 'android/app/' path and addition "-keep class tv.danmaku.ijk.media.player.** {*;}" into the file, when i rerty the build "flutter build apk && flutter install " that it is work well.
> > 
> > 
> > 在`android/app/`下新建`proguard-rules.pro`，成功！
> > ```
> > -keep class tv.danmaku.ijk.media.player.** {*;}
> > ```
> 
> 解决了。确实是我放错了混淆文件位置

可以加个联系方式指导一下嘛？谢谢
