### ISSUE TITLE
[Need help] Confirm if rtmp is working

### ISSUE THREAD

**Issue by daniel-v** [CaiJingLong/flutter_ijkplayer#23]
Hello @CaiJingLong! Awesome stuff, thanks for all the effort you put into this.

I would like to confirm that `rtmp` protocol is working as you inteded it to. I created an app based on your english readme, all network playback works as they should but rtmp. All I get is a black screen. 

On the other end of the stream, I used nginx-rtmp module. I confirmed that the stream works by viewing it with an rtmp-capable player: `MX Player`.

**Comment by CaiJingLong** [comment]
It seems that the library of the Android part has a problem after I recompile it, and I will fix it as soon as possible.

**Comment by CaiJingLong** [comment]
Try to use version 0.2.1 .
