### ISSUE TITLE
[Need help]ijkplayer编译支持armv7后，项目提示找不到IJKMPMoviePlayerVideoRotationNotification

### ISSUE THREAD

**Issue by amazingrace** [CaiJingLong/flutter_ijkplayer#231]
Hi CaiJingLong
你好，我在项目用了您的这个库，觉得非常好，但是在打包的时候提示该库不支持armv7。
我在这个链接里看到您的回复是可以手动添加对armv7的支持，我就尝试着编译出了支持armv7和openssl的ijkMediaFramework。
[issues/185](https://github.com/CaiJingLong/flutter_ijkplayer/issues/185)
方法是这里
[ijkplayer/issues/4150](https://github.com/bilibili/ijkplayer/issues/4150)
但是我把打包好的IJKMediaFramework.framework拖进项目/Pods/FlutterIJK/中打包发现，提示找不到IJKMPMoviePlayerVideoRotationNotification和IJKMPMoviePlayerVideoRotationRotateUserInfoKey，请问是否您的这个库有做过哪些修改，涉及到以上两处变量？
谢谢。
![image](https://user-images.githubusercontent.com/6355669/80568816-4c34a700-8a2a-11ea-9169-6d585567f574.png)

**Comment by CaiJingLong** [comment]
iOS原本不支持纹理渲染, 本项目因为添加了对于iOS的纹理支持, 所以和bilibili官方的源码有非常大差异, 并且在这基础上添加了一些通知

全部修改如下: 

https://gitee.com/kikt/ijkplayer_thrid_party/compare/98d52eaf8d4d2f470353536fa95dd2c388a7220f...master

git clone https://gitee.com/kikt/ijkplayer_thrid_party.git

你需要clone并使用这个源码进行编译

**Comment by amazingrace** [comment]
> iOS原本不支持纹理渲染, 本项目因为添加了对于iOS的纹理支持, 所以和bilibili官方的源码有非常大差异, 并且在这基础上添加了一些通知
> 
> 全部修改如下:
> 
> https://gitee.com/kikt/ijkplayer_thrid_party/compare/98d52eaf8d4d2f470353536fa95dd2c388a7220f...master
> 
> git clone https://gitee.com/kikt/ijkplayer_thrid_party.git
> 
> 你需要clone并使用这个源码进行编译

谢谢你的回复，已经顺利编译通过了。
