### ISSUE TITLE
[Bug]关于客户端闪退问题报告

### ISSUE THREAD

**Issue by 0-php** [CaiJingLong/flutter_ijkplayer#25]
我经过测试其实不是 安卓9.0会崩溃而是因为在
~/project1/android/build.gradle 中加入了
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"

这段代码的话 我通过正常的发包 flutter build apk --release 然后下载到手机上后会出现 闪退的情况 不止安卓9.0我的安卓7.0也会出现闪退
不是做安卓出来的遇到这个问题很痛苦 有没有办法解决？
今天试了很多办法都不行

系统信息：
➜  huangua2 flutter doctor -v          
[✓] Flutter (Channel stable, v1.2.1, on Mac OS X 10.14.3 18D109, locale zh-Hans-CN)
    • Flutter version 1.2.1 at /Users/sam/flutter
    • Framework revision 8661d8aecd (8 weeks ago), 2019-02-14 19:19:53 -0800
    • Engine revision 3757390fa4
    • Dart version 2.1.2 (build 2.1.2-dev.0.0 0a7dcf17eb)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/sam/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/sam/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 34.0.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Ultimate Edition (version 2018.2.4)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.io/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • OD103 • a013c25f • android-arm64 • Android 7.1.1 (API 25)

! Doctor found issues in 1 category.

**Comment by 0-php** [comment]
主要是需要下载的如果用 flutter run  apk --release 是可以正常执行的

**Comment by CaiJingLong** [comment]
非本库的问题 请到 https://stackoverflow.com/ 这样的地方提问

**Comment by CaiJingLong** [comment]
提示一下: android的问题 
你需要使用logcat查询对应的crash日志, 才能对症下药.
什么都没有的情况下,没有人能帮你解决问题.

如果不知道怎么查看logcat日志可以使用搜索引擎

**Comment by jendy2012** [comment]
buildTypes {
        release {
            ndk{
                //这里其实我觉可以直接是用"armeabi-v7a"，但国内几个大哥之前使用的都是"armeabi"
//                abiFilters "armeabi"
                abiFilters "armeabi-v7a"
            }
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
        debug {
            ndk {
                //这里要加上，否则debug包会出问题,后面三个为可选，x86建议加上不然部分模拟器回报错
                abiFilters "armeabi","armeabi-v7a","arm64-v8a", "x86"
            }
        }
    }

这个解决闪退问题。
