### ISSUE TITLE
[Need help]No visible @interface for 'IJKFFMoviePlayerController' declares the selector 'framePixelbuffer'

### ISSUE THREAD

**Issue by phoche** [CaiJingLong/flutter_ijkplayer#26]
iOS 是swift 工程，build 时 copyPixelBuffer 方法里有报错无法编译

**Comment by CaiJingLong** [comment]
稍等 我尝试一下

**Comment by CaiJingLong** [comment]
稍等 我尝试一下

**Comment by CaiJingLong** [comment]
iOS部分目前因为我使用的是IjkPlayer默认的库制作方式,其中包含了一些静态库, 在oc上是可以正常使用的

如果你在原生中没有引用使用pod引用第三方的swift的库, 可以暂时在项目ios文件夹下的Podfile中

搜索 `use_frameworks!` 将这句注释掉或者删除掉(注释使用#)使用, 如果引用了第三方的swift库,你可能暂时无法使用这个插件库

我在近期尝试解决一下, 如果没问题的话会在下一个版本发布的时候更新以支持swift

**Comment by CaiJingLong** [comment]
Fixed in #27.

Try update version to 0.2.2 .
