### ISSUE TITLE
可以自定义视频播放长度么？

### ISSUE THREAD

**Issue by jendy2012** [CaiJingLong/flutter_ijkplayer#28]
我可以自定义视频播放长度么？
比如，非会员，只能观看一分钟视频。

**Comment by CaiJingLong** [comment]
自己通过代码控制即可

举例:
1. 监听当前播放进度
2. 当超过1分钟时判断当前身份,是会员,则忽略,不是则暂停播放弹出弹框

具体逻辑自己去实现

如果是需要在界面上有更改,比如非会员时进度条只有1分钟,自己按照[Readme](https://github.com/CaiJingLong/flutter_ijkplayer#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%A7%E5%88%B6%E5%99%A8-ui)中的自定义控制器UI方式去修改
