### ISSUE TITLE
Android 播放短视频卡死！

### ISSUE THREAD

**Issue by AlanGrey** [CaiJingLong/flutter_ijkplayer#282]
1.短视频（30s~60s）播放到最后几秒，大概率出现卡死！
2.此时暂停之后，再继续播放进度条时间增加，甚至会超出视频总时间，但视频画面没动；在暂停之后，进度条时间回到卡死的秒数；

原因：看后台输出log，应该是最后几秒get_buffer() failed ,之后IjkMediaPlayer报了 Error (-10000,0) 的错误，不知道哪里没有处理好（NotifyChannel 是有对应log，但flutter 监听没有接收到error异常回调）；导致界面还是正常显示，就会出现上述2情况；

另外，想问get_buffer()，会受什么情况影响才会失败呢？视频源流波动?

**Comment by AlanGrey** [comment]
已经找到问题所在点了

**Comment by Wisdozzh** [comment]
你咋解决的？
