### ISSUE TITLE
支持flv视频流嘛，请问[Need help]

### ISSUE THREAD

**Issue by DricHao** [CaiJingLong/flutter_ijkplayer#29]
想在IOS播放FLV视频流

**Comment by CaiJingLong** [comment]
编译选项对应的文件:
https://gitee.com/kikt/ijkplayer_thrid_party/blob/master/config/module.sh

该文件含义咨询 [bilibili/ijkplayer](https://github.com/bilibili/ijkplayer)

额外的格式本库不做原生支持,请[自定义编译](https://github.com/CaiJingLong/flutter_ijkplayer/blob/master/compile-cn.md)
