### ISSUE TITLE
直播流，放一会就自己停了，要重新点播放按钮

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#35]

**Comment by CaiJingLong** [comment]
提供一个公网可用的流地址

**Comment by CaiJingLong** [comment]
flutter doctor -v

然后说一下是iOS还是android 或者都有问题

**Comment by Seifon** [comment]
http://js.flv.huya.com/huyalive/94525224-2460685313-10568562945082523648-2789274524-10057-A-0-1.flv?wsSecret=9b67d35535b6956aec37815c21e43cc8&wsTime=5cbbea84&ratio=2000

**Comment by Seifon** [comment]
$ flutter doctor -v
[✓] Flutter (Channel dev, v1.4.18, on Mac OS X 10.14.4 18E194d, locale zh-Hans-CN)
• Flutter version 1.4.18 at /Users/xxxx/dev-tool/flutter
• Framework revision 8bea3fb2eb (9 days ago), 2019-04-11 13:11:22 -0700
• Engine revision 72986c39ea
• Dart version 2.2.1 (build 2.2.1-dev.3.1 None)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
• Android SDK at /Users/xxxxx/dev-tool/Android_Sdk
• Android NDK location not configured (optional; useful for native profiling support)
• Platform android-28, build-tools 28.0.3
• ANDROID_HOME = /Users/xxxxxx/dev-tool/Android_Sdk
• Java binary at: /Library/Java/JavaVirtualMachines/jdk1.8.0_191.jdk/Contents/Home/bin/java
• Java version java version "1.8.0_191"
• All Android licenses accepted.

[!] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
• Xcode at /Applications/Xcode.app/Contents/Developer
• Xcode 10.2.1, Build version 10E1001
✗ Verify that all connected devices have been paired with this computer in Xcode.
If all devices have been paired, libimobiledevice and ideviceinstaller may require updating.
To update with Brew, run:
brew update
brew uninstall --ignore-dependencies libimobiledevice
brew uninstall --ignore-dependencies usbmuxd
brew install --HEAD usbmuxd
brew unlink usbmuxd
brew link usbmuxd
brew install --HEAD libimobiledevice
brew install ideviceinstaller
• ios-deploy 1.9.4
• CocoaPods version 1.5.3

[!] Android Studio (not installed)
• Android Studio not found; download from https://developer.android.com/studio/index.html
(or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] IntelliJ IDEA Ultimate Edition (version 2018.3.6)
• IntelliJ at /Applications/IntelliJ IDEA.app
• Flutter plugin version 34.0.2
• Dart plugin version 183.6156.10

[✓] Connected device (2 available)
• M10 • 012345678FDBCDEF • android-arm • Android 7.0 (API 19)
• iPhone Xʀ • 70E9175D-7D9C-xxxx-B80A-AXS37E374ED4 • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-2 (simulator)

! Doctor found issues in 2 categories.

**Comment by Seifon** [comment]
IOS和安卓都有这个问题

**Comment by CaiJingLong** [comment]
虎牙的直播流可能有限制, 至少你提供的url我这里鉴权失败了 403错误

**Comment by Seifon** [comment]
我试了 腾讯超级播放器 和 video_player都没有这个问题的，你检查一下看看是不是播放视频时，流下载不稳定导致的这个问题呢

**Comment by CaiJingLong** [comment]
这里只是接入了 bilibili/ijkplayer的sdk到flutter端, 播放时的具体逻辑我这里不清楚.
关于内部的播放问题或网络问题,我这里无法调试,也不知道原因.

**Comment by Seifon** [comment]
奇怪了，我编译了IOS端的ijk demo，播放都没出现这个断流的问题呀。您要不看看是不是纹理接入后，哪里没做好处理呢。

![](https://ws3.sinaimg.cn/large/005BYqpgly1g2f8ei6sxvj31120ku41w.jpg)

**Comment by CaiJingLong** [comment]
播放过程的逻辑不是由我处理的

**Comment by CaiJingLong** [comment]
另外: 鉴于我无法播放
建议你提供一些**使用插件时的日志**和调用处的相对完整的**可运行代码**

**Comment by CaiJingLong** [comment]
根据置顶issue规则, 暂时关闭
如果有后续可用于复现的方案, 可以重新open
