### ISSUE TITLE
[Need help] Is there a way to disable the beep sound when volume is changed in the video player?

### ISSUE THREAD

**Issue by dheerajbred** [CaiJingLong/flutter_ijkplayer#37]
Hi,

I know this is not an issue. But I'd really need some help in disabling the beep sound when the volume is changed in the video player.

Any suggestion is appreciated.

Thanks :)

**Comment by CaiJingLong** [comment]
The beep sound is probably usually made by the system, and you may need to check the android/iOS solution.

I don't know how to solve this problem, you can wait for someone else to answer.
