### ISSUE TITLE
[Bug]安卓mp4 全屏和非全屏切换导致视频重置问题

### ISSUE THREAD

**Issue by zzAbel** [CaiJingLong/flutter_ijkplayer#38]
安卓正常播放时，普通切换至全屏、全屏切换至普通 都会导致视频从头开始播放，请问有遇到过这个问题吗？

之前使用chewie插件也有这种情况

**Comment by zzAbel** [comment]
问题已解决

**Comment by mrtian** [comment]
怎么解决的？

**Comment by CaiJingLong** [comment]
转屏导致的重绘只是重新build而已, 不会引起controller本身的重新创建, 理论上不影响播放进度
我本人在实际的使用中也没有遇到
如果你遇到了可以考虑状态提升的解决方案, controller 本身应该是page级的成员变量.

**Comment by mrtian** [comment]
了解了
