### ISSUE TITLE
希望能做一个 腾讯超级播放器 的插件

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#39]
用了一下腾讯播放器的Demo，感觉挺好的，在IJK的基础上做了更好的封装。

希望你能出一个这个播放器的插件。

文档在这：
https://cloud.tencent.com/document/product/881/20214

**Comment by CaiJingLong** [comment]
查询了文档, 播放器部分是闭源的, 仅UI部分开源, 无法外接纹理至flutter
