### ISSUE TITLE
安卓端，退出全屏时，屏幕不能变竖屏

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#40]
点退出全屏按钮后，不能回到竖屏模式

**Comment by CaiJingLong** [comment]
有问题的话 请按照预设模板提供对应的信息

如此空泛的描述无法定位问题

请clone或下载仓库,使用仓库中的example来查看代码的用法

**Comment by jendy2012** [comment]
1.在手机横向放置的时候，点退出全屏按钮，整个页面会变成横屏（在自动旋转打开的情况）。不开自动旋转没有这个问题。
2.有没有自动退出全屏的事件。（使用默认UI）的时候。

**Comment by qq125183592** [comment]
我是退出时调用IjkManager.setPortrait(); 强制转了方向

**Comment by CaiJingLong** [comment]
> 1.在手机横向放置的时候，点退出全屏按钮，整个页面会变成横屏（在自动旋转打开的情况）。不开自动旋转没有这个问题。
> 2.有没有自动退出全屏的事件。（使用默认UI）的时候。

1. 这个问题是这样的, 因为应用本身的方向状态并不能确认, 我不能确认退出后是否应该锁定屏幕方向为竖屏(比如iPad或安卓平板横屏居多), 所以库中能做的只有再退出全屏后解锁屏幕方向锁定,  让屏幕可以跟随当前的方向
2. 自动退出是没有的, 不过你如果是需要播放完毕自动退出, 是可以使用状态监听配合Navigator.pop来达到退出全屏的效果的



> 我是退出时调用IjkManager.setPortrait(); 强制转了方向
这个方法本身也是有意暴露给使用者的, 以便于针对自己的应用情况自主调用.
