### ISSUE TITLE
请问，有调整画面比例的APi吗？

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#42]
指定长宽后，画面不能铺满，有两条黑边，要是有调整画面比例的api就好了

**Comment by CaiJingLong** [comment]
如果你使用过任何视频软件就会发现大部分视频都有"黑边"
需要自定义界面的话 可以参考[文档](https://github.com/CaiJingLong/flutter_ijkplayer#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BA%B9%E7%90%86%E7%95%8C%E9%9D%A2)

结合FittedBox实现自己的视频纹理显示逻辑

**Comment by CaiJingLong** [comment]
或者,使用`IjkMediaController`结合`Texture`,`Stack` 实现自己的显示逻辑.

**Comment by zszen** [comment]
使用组件AspectRatio

**Comment by wtus** [comment]
可通过 _ijkMediaController.getVideoInfo() 拿到视频宽高属性，利用楼上说的 AspectRatio 实现，不过建议还是提供对应的api。
本库还是很好用的
