### ISSUE TITLE
请问一下flutter[Need help]

### ISSUE THREAD

**Issue by ywui** [CaiJingLong/flutter_ijkplayer#43]
请问一下flutter有几种方式播放视频，除了纹理的方式还有其他的吗 目前纹理的方式是不是 性能最好的？

**Comment by CaiJingLong** [comment]
还有PlatformView的方式
也就是通过AndroidView/UIKitView的方式

常规个人/团队能使用的只有这两种

**Comment by ywui** [comment]
各有什么优势啊

**Comment by CaiJingLong** [comment]
这个你可以查看一下相关的文章,如果有原生开发经验,不用我展开说看看源码大概就知道了

没有原生经验的话, 不是一两句话能说明白的

简单理解的话,视频这样纯展示,没有交互的用纹理比较好

如果有交互的,比如地图/WebView ,需要用PlatformView

**Comment by ywui** [comment]
如果从性能上来说呢

**Comment by CaiJingLong** [comment]
性能这个东西没实测过,不知道
