### ISSUE TITLE
希望能够支持 软解和硬解切换

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#45]
看了GSYplayer的文章，ijk好像是支持切换解码方式的，不知道flutter_ijk可不可以提供出相应的API呢？

https://www.jianshu.com/p/220b00d00deb

**Comment by CaiJingLong** [comment]
这个建议你通过自定义的代码去实现, 原则上来说不考虑加入内置功能

因为硬解需要硬件支持, IJKPlayer中开启硬解后的策略是: 优先硬解,硬解不成功软解,但硬解可能黑屏或者视频方向不对,这个时候不会触发自定切换软解的操作

换句话说硬解在实际应用中有很大的风险

---

开启的代码可以搜索IJKPlayer的option使用,然后使用[自定义option](https://github.com/CaiJingLong/flutter_ijkplayer#%E8%87%AA%E5%AE%9A%E4%B9%89-option)中的方式来设置

步骤如下:
1. 自定义UI设置一个切换软硬解按钮
1. 记录当前播放时间
1. 根据当前硬解或软件的状态 设置硬解/软解参数
1. 重新设置播放源
1. 跳转到记录的时间
1. 播放

**Comment by Seifon** [comment]
> 这个建议你通过自定义的代码去实现, 原则上来说不考虑加入内置功能
> 
> 因为硬解需要硬件支持, IJKPlayer中开启硬解后的策略是: 优先硬解,硬解不成功软解,但硬解可能黑屏或者视频方向不对,这个时候不会触发自动切换软解的操作
> 
> 换句话说硬解在实际应用中有很大的风险
> 
> 开启的代码可以搜索IJKPlayer的option使用,然后使用[自定义option](https://github.com/CaiJingLong/flutter_ijkplayer#%E8%87%AA%E5%AE%9A%E4%B9%89-option)中的方式来设置
> 
> 步骤如下:
> 
> 1. 自定义UI设置一个切换软硬解按钮
> 2. 记录当前播放时间
> 3. 根据当前硬解或软件的状态 设置硬解/软解参数
> 4. 重新设置播放源
> 5. 跳转到记录的时间
> 6. 播放

切换软解的参数是什么呢？百度查了一下，没有找到。想开启flv软解试试
