### ISSUE TITLE
IjkPlayer 自定义 controllerWidgetBuilder

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#47]
自定义的几个地方，希望能够不限制类型和参数个数额，我想自定义一个controllerWidgetBuilder，需要多传一个对象参数进去，发现无法通过编译。

另外，希望几个自定义的地方，能够放开类型限制，或者做一下更好的调整

```
typedef Widget IJKControllerWidgetBuilder(IjkMediaController controller);

/// default create IJK Controller UI
Widget defaultBuildIjkControllerWidget(IjkMediaController controller) {
  return DefaultIJKControllerWidget(
    controller: controller,
//    verticalGesture: false,
//    horizontalGesture: false,
  );
}
```

我想这样传，发现过不了编译：

```
Widget qIjkControllerWidget(IjkMediaController controller, HomeItem homeItem) {
  return QIjkController(
    controller: controller,
    homeItem: homeItem,
//    verticalGesture: false,
//    horizontalGesture: false,
  );
}
```

**Comment by Seifon** [comment]
以前用video_player的时候，UI控制用的是这个插件：chewie

他里面有一些比较好的控制代码，可以参考一下额，这样应该会减少一些代码量。希望对你有帮助

https://pub.dartlang.org/packages/chewie

**Comment by 0-php** [comment]
controllerWidgetBuilder: (mediaController){

          return Container(child: Stack(
            children: <Widget>[
              Center(child:Container(child: Stack(
                children: <Widget>[
                  new Positioned(
                      left: 130.0,
                      top: 30.0,
                      child: new Container(
                        width: 100.0,
                        height: 80.0,
                        decoration: new BoxDecoration(color: Colors.red),
                        child: Title(
                        color: Colors.white,
                            child: Banner(
                          child: null,
                          message: 'ffDEBUG21312312123',
                          textDirection: TextDirection.rtl,
                          location: BannerLocation.bottomEnd,
                        )),
                      )
                  ),

                  DefaultIJKControllerWidget(controller: mediaController),
                ],

              )))

            ],
          ));
          return DefaultIJKControllerWidget(controller: mediaController);
        },

这样传是可以的你把 DefaultIJKControllerWidget 再封装一层就可以了，但是我也遇到了一个问题就是在全屏的情况下只有 DefaultIJKControllerWidget 生效了 上面的banner在全屏的情况下出不来好难受
@CaiJingLong  请问全屏模式下应该怎么处理？

**Comment by 0-php** [comment]
已经解决了，全屏的时候他用showdialog重写创建了一个dialog所以在原来的窗口上绘制是无效的需要在_buildFullScreenMediaController中再绘制一遍就可以了目前只能这样解决

**Comment by CaiJingLong** [comment]
@0-php 
全屏不能自定义界面的问题我后面会解决一下

---

因为视频控制器的UI界面众口难调, 所以开放了外置自定义UI的方案

自定义最强的方案是只使用IjkMediaController来控制视频, 其余所有的界面,控制等逻辑自己来写

**Comment by CaiJingLong** [comment]
> 自定义的几个地方，希望能够不限制类型和参数个数额，我想自定义一个controllerWidgetBuilder，需要多传一个对象参数进去，发现无法通过编译。
> 
> 另外，希望几个自定义的地方，能够放开类型限制，或者做一下更好的调整
> 
> ```
> typedef Widget IJKControllerWidgetBuilder(IjkMediaController controller);
> 
> /// default create IJK Controller UI
> Widget defaultBuildIjkControllerWidget(IjkMediaController controller) {
>   return DefaultIJKControllerWidget(
>     controller: controller,
> //    verticalGesture: false,
> //    horizontalGesture: false,
>   );
> }
> ```
> 
> 我想这样传，发现过不了编译：
> 
> ```
> Widget qIjkControllerWidget(IjkMediaController controller, HomeItem homeItem) {
>   return QIjkController(
>     controller: controller,
>     homeItem: homeItem,
> //    verticalGesture: false,
> //    horizontalGesture: false,
>   );
> }
> ```

自定义封装的问题 可以参考楼上的朋友 给出了方案

**Comment by Seifon** [comment]
屏幕旋转后，不知道该怎样实现全屏啊。目前都是需要点全屏按钮才会实现全屏的效果。

如果是屏幕旋转，屏幕无法实现真正的全屏。

我试过在build方法里面判断屏幕方向，然后跳转路由到全屏界面。但发现这种做法不可取，会报错。

不知道你们有没有好的解决方案呢？

**Comment by Seifon** [comment]
> DefaultIJKControllerWidget

这样做，只是在DefaultIJKControllerWidget的基础上漂浮了一些组件呀，貌似不能实现自定义里面的控件额。我想自定义DefaultIJKControllerWidget里面的控件，这些空间又依赖外部传进来一个对象参数，所以这就有点尴尬😅了

**Comment by Seifon** [comment]
> `
> 
> ```
> controllerWidgetBuilder: (mediaController){
> 
>           return Container(child: Stack(
>             children: <Widget>[
>               Center(child:Container(child: Stack(
>                 children: <Widget>[
>                   new Positioned(
>                       left: 130.0,
>                       top: 30.0,
>                       child: new Container(
>                         width: 100.0,
>                         height: 80.0,
>                         decoration: new BoxDecoration(color: Colors.red),
>                         child: Title(
>                         color: Colors.white,
>                             child: Banner(
>                           child: null,
>                           message: 'ffDEBUG21312312123',
>                           textDirection: TextDirection.rtl,
>                           location: BannerLocation.bottomEnd,
>                         )),
>                       )
>                   ),
>                   DefaultIJKControllerWidget(controller: mediaController),
>                 ],
>               )))
>             ],
>           ));
>         },
> ```
> 
> `
> 这样传是可以的你把 DefaultIJKControllerWidget 再封装一层就可以了，但是我也遇到了一个问题就是在全屏的情况下只有 DefaultIJKControllerWidget 生效了 上面的banner在全屏的情况下出不来好难受
> @CaiJingLong 请问全屏模式下应该怎么处理？

这样做，只是在DefaultIJKControllerWidget的基础上漂浮了一些组件呀，貌似不能实现自定义里面的控件额。我想自定义DefaultIJKControllerWidget里面的控件，这些空间又依赖外部传进来一个对象参数，所以这就有点尴尬😅了

**Comment by 0-php** [comment]
@Seifon 他的controllerWidgetBuilder 的数据没有主动推送数据是按照事件更新数据的但是他的DefaultIJKControllerWidget 这个类里面没有实时简单屏幕方向所以你那边就不会选择屏幕了，这块可能要加一个定时器去实时监听

**Comment by CaiJingLong** [comment]
> 屏幕旋转后，不知道该怎样实现全屏啊。目前都是需要点全屏按钮才会实现全屏的效果。
> 
> 如果是屏幕旋转，屏幕无法实现真正的全屏。
> 
> 我试过在build方法里面判断屏幕方向，然后跳转路由到全屏界面。但发现这种做法不可取，会报错。
> 
> 不知道你们有没有好的解决方案呢？

点击全屏按钮,跳到dialog中显示,是我综合了各种方案后觉得实现起来最不容易出错的方案,实现相对会简单很多

之前试过Overlay 也试过用Navigator开新页面  效果都不好

根据屏幕方向自动旋转全屏方案我在example里写过示例

1. 判断屏幕方向
2. build方法中, 如果是竖屏,按照正常的情况来布局,如果是横屏,则不用Scaffold ,直接填充一个IjkPlayer
