### ISSUE TITLE
偶尔会出现 视频无法关闭

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#49]
使用的同一个IjkMediaController去播放视频。

每次播放下一个视频时，我都掉用了销毁相关的方法。

刚开始没有问题，可是播放几个视频后，就出现有的视频源一直在播放，声音一直存在。

我写的关闭方法是：

await _ijkController.pauseOtherController();
await _ijkController.pause();
await _ijkController.stop();
await _ijkController.reset();

**Comment by CaiJingLong** [comment]
使用同一个控制器来播放其他的媒体,理论上 你只需要重新设置DataSource即可

我在重新设置视频源的时候会做dispose上一的操作

https://github.com/CaiJingLong/flutter_ijkplayer/blob/255831f72452fd54d7d181e96b3ef1290c0a097b/lib/src/controller/controller.dart#L149-L151

如果你有可以复现的代码,请贴出来,我在确认是bug的情况下会修复

**Comment by Seifon** [comment]
```
/**
   * 重置播放器控件
   */
  void dispose() async {
    if (_ijkController != null) {
      await _ijkController.pauseOtherController();
      await _ijkController.pause();
      await _ijkController.stop();
      await _ijkController.reset();
    }
}

void play() async {
   await dispose();
  _ijkController
        .setNetworkDataSource("url",
            autoPlay: true)
        .then((_) async {    });
}
```

**Comment by Seifon** [comment]
这种情况是偶现的，往往是连续播放了好几个视频，才会出现这种现象。

**Comment by 0-php** [comment]
@Seifon 应该是你跳转路由的时候有问题
你跳转的时候可以试下这样
`maintainState:false //加上这个属性`

`
Navigator.push(context, new MaterialPageRoute(maintainState:false,builder: (BuildContext context){
          return new DetailView(vod_id:data[index]['vod_id'],MoviceName: data[index]['vod_name']);
        }));
`

**Comment by Seifon** [comment]
没有跳转的，视频都在一个列表里面，点一下就播放那种，不会跳转到其它页面啊

**Comment by Seifon** [comment]
改成跳转的那种，发现这种重复播放的情况就必现了。这是什么原因呢，按理只有一个_ijkController，不会出现这种现象啊。麻烦您检查一下什么原因吧

**Comment by 0-php** [comment]
@Seifon 你路由跳转的时候旧的页面没有释放掉。。

**Comment by Seifon** [comment]
有的时候，跳转页面，不想把上一个页面的资源释放掉额，比如要做一个小窗口播放，这种情况，就不能释放资源啊。按理来说，全局只定义一个_ijkController，应该是静态唯一的，多个view附着一个controller，不应该出现重复播放的现象呀。希望您能再优化一下。

**Comment by CaiJingLong** [comment]
没有代码, 这种描述方法根本无法定位问题
需要有一个最小可复现的代码示例,否则问题就只能挂着

或者你解决后可以提PR

**Comment by CaiJingLong** [comment]
可复现的代码,简单意思就是:
这份代码,我拿过来**直接可以运行到设备上**
然后,经过一定的步骤,会复现bug

**Comment by CaiJingLong** [comment]
我在代码中加了状态判断和对应的限制, 如果再出现无法dispose的情况, 请继续留言或重新开一个新的issue.
我先暂时关闭这个issue, 如果还有问题, 请重新打开, 并提供可复现的完整Example代码.
