### ISSUE TITLE
项目很棒，希望大佬能继续维护

### ISSUE THREAD

**Issue by msterzhang** [CaiJingLong/flutter_ijkplayer#5]
项目很棒，十分感谢，希望大佬能继续维护

**Comment by CaiJingLong** [comment]
我会积极维护这个项目,不过作为一个android出身的人,iOS部分力有不逮
并且在研究IjkPlayer的过程中发现了一些方案的实现上,iOS和android的ijkplayer部分会有不同,所以预计很多比较容易在android实现的东西在iOS端很难实现,反之亦然.

总体来说尽量保证主体稳步前行, 一些相对难以实现或flutter比较限制的东西只能放弃或等待完善
