### ISSUE TITLE
[Need help]flutter build ios时会有异常

### ISSUE THREAD

**Issue by qq125183592** [CaiJingLong/flutter_ijkplayer#52]
连接手机跑起来没问题，想编译打包，执行flutter build ios时出现以下错误，没做过ios原生，求大神帮解答

Xcode's output:
↳
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    ld: warning: ignoring file /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/FlutterIJK/IJKMediaFramework.framework/IJKMediaFramework, missing required architecture armv7 in file
    /Users/yujie/AndroidStudioProjects/flutter_app/ios/Pods/FlutterIJK/IJKMediaFramework.framework/IJKMediaFramework (3 slices)
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_IJKFFOptions", referenced from:
          objc-class-ref in libflutter_ijkplayer.a(CoolFlutterIJK.o)
      "_IJKMPMoviePlayerVideoRotationRotateUserInfoKey", referenced from:
          -[CoolIjkNotifyChannel movieRotationChange:] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerPlaybackStateDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerVideoRotationNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerPlaybackDidFinishNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
          objc-class-ref in libflutter_ijkplayer.a(CoolFlutterIJK.o)
      "_IJKMPMoviePlayerLoadStateDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Encountered error while building for device.

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_ijkplayer/issues/22#issuecomment-481976222

**Comment by qq125183592** [comment]
非常感谢，解决了

**Comment by zszen** [comment]
remove armv7
