### ISSUE TITLE
[Need help]直播时的手势问题

### ISSUE THREAD

**Issue by qq125183592** [CaiJingLong/flutter_ijkplayer#59]
在直播时，如果用手势左右滑动会操作进度，导致直播内容异常，请问该怎么选择性的屏蔽部分手势功能呢？

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_ijkplayer#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8E%A7%E5%88%B6%E5%99%A8-ui

查看这部分文档, 自定义属性`controllerWidgetBuilder`

然后结合默认控制器

https://github.com/CaiJingLong/flutter_ijkplayer/blob/6c28d5954425a812a135df07436b86825656c3c1/lib/src/widget/controller_widget_builder.dart#L28-L38

使用 horizontalGesture 达到屏蔽横向手势的目的

**Comment by qq125183592** [comment]
好的，谢谢
