### ISSUE TITLE
How to customize compile options?

### ISSUE THREAD

**Issue by ened** [CaiJingLong/flutter_ijkplayer#6]
@CaiJingLong do you have a suggested workflow to strip down the package to include only the required codecs / formats for a project?

I would try to:
 - fork, recompile, upload https://github.com/CaiJingLong/flutter_ijkplayer_pod
 - fork this project
   - let iOS podspec point to forked `flutter_ijkplayer_pod` repo with the files
   - probably something similar for Android GSYPlayer dependency?

**Comment by CaiJingLong** [comment]
1. clone/download the project 
1. add your library path to pubspec.yaml
1. `$ git clone https://gitee.com/kikt/ijkplayer_thrid_party.git`
1. see https://github.com/bilibili/ijkplayer Readme to compile a framework.
1. copy the IJKMediaFramework.framework to your flutter_ijkplayer path
Look like the image
![image](https://user-images.githubusercontent.com/14145407/55271982-ffdfda80-52f0-11e9-8b3f-0b9db7b0a526.png)
1. update your flutter_ijkplayer.podspec use the library. 
Look like the image
![image](https://user-images.githubusercontent.com/14145407/55271999-459ca300-52f1-11e9-8923-cb924c374469.png)

**Comment by CaiJingLong** [comment]
Compile framework step:
1. git clone https://gitee.com/kikt/ijkplayer_thrid_party ijkplayer
2. edit your config/module.sh
3. If you need https protocol, compile openssl
4. compile ffmpeg
5. open IjkMediaPlayer in xcode.
6. compile IjkMediaPlayer framework.
7.  lipo x86 i386 arm64 framework.
8. find the framework and copy it to your project's flutter_ijkplayer.

**Comment by CaiJingLong** [comment]
I add a compile [document](https://github.com/CaiJingLong/flutter_ijkplayer/blob/master/compile.md).
