### ISSUE TITLE
安卓9.0，截图会闪退

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#60]

**Comment by 0-php** [comment]
我试了P30是正常的

**Comment by CaiJingLong** [comment]
日志?

**Comment by Seifon** [comment]
> 日志?

我也是用户反馈给我说有这个问题额，没有日志啊

**Comment by CaiJingLong** [comment]
建议你加入崩溃的反馈
比如友盟/bugly/蒲公英之类的工具, 在崩溃后可以上传日志到对应sdk的后台

这样的工具目前还是比较多的, 具体的使用方法可以自行百度

----

关于这个问题,没有日志的话,目前无法解决...
