### ISSUE TITLE
老哥话说视频缓存在flutter怎么去做啊

### ISSUE THREAD

**Issue by onemengxin** [CaiJingLong/flutter_ijkplayer#61]
老哥话说视频缓存在flutter怎么去做啊，例如电视剧缓存集数什么的，或者老哥要不要考虑搞个插件什么的

**Comment by CaiJingLong** [comment]
现行的做法,肯定是自建数据库保存,数据库字段基本应该包含: id, url, 本地路径, 下载进度,下载时间, 描述等字段
稍微提一下, "边下边播" 是另一个范畴, 逻辑复杂,不讨论

没有做这种"插件"的打算

**Comment by CaiJingLong** [comment]
而且, 这种需求和业务逻辑深耦合, "插件"没太大意义
况且有了这个,又可能想要"录"直播流接入离线下载体系等等的扩展需求,实在是没有时间来做了,大而全的框架很难实现

**Comment by Aaron009** [comment]
边下边播还是蛮重要的，希望能重新打开此问题。
我研究了一下原理。
https://www.jianshu.com/p/4745de02dcdc
好像是通过在APP里面内置一个代理服务器实现的。
