### ISSUE TITLE
iOS全屏幕的问题,因为项目不能旋转屏幕,所以设置了xcode只能竖屏,点击全屏就闪退

### ISSUE THREAD

**Issue by programmerElephant** [CaiJingLong/flutter_ijkplayer#62]
关闭过后在player中旋转监听屏幕也不会走～
![image](https://user-images.githubusercontent.com/22141267/57615747-02e80f00-75af-11e9-9aa9-e032cdafe0a0.png)

**Comment by programmerElephant** [comment]
有什么解决办法吗？谢谢你拉～

**Comment by 0-php** [comment]
可以用低版本的暂时用下 比如 0.1.8

**Comment by dmlzj** [comment]
顶一下，同求解决方法！

**Comment by xjrad** [comment]
有一样的问题，0.3.0版本点击全屏闪退

**Comment by MessiMercy** [comment]
同求解决办法

**Comment by programmerElephant** [comment]
新写一个页面用来播放全屏，然后通过和ios原生交互来动态改变这个页面是否可以全屏。




------------------ 原始邮件 ------------------
发件人: "MessiMercy"<notifications@github.com>;
发送时间: 2019年7月3日(星期三) 上午10:39
收件人: "CaiJingLong/flutter_ijkplayer"<flutter_ijkplayer@noreply.github.com>;
抄送: "陈洲洲"<474116207@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CaiJingLong/flutter_ijkplayer] iOS全屏幕的问题,因为项目不能旋转屏幕,所以设置了xcode只能竖屏,点击全屏就闪退 (#62)




同求解决办法

**Comment by CaiJingLong** [comment]
说实话... 我个人没有想到特别好的办法
直接在竖屏情况下通过"旋转"IjkPlayer 90度(270度)并且充满全屏肯定是一个办法, 但是这种情况下可能不能隐藏系统的状态栏, 或者有其他问题, 比如在脑补未经验证的情况下个人感觉可能会有手势的问题

----
另外我因为最近有工作上的事情, 没有太多的时间解决这个问题, 所以这个问题可能会搁置一段时间, 后面我会通过一个配置选项来让用户主动"告诉"IjkPlayer是使用"旋转"的方式来显示全屏, 还是现在这种强制横屏的方式

**Comment by CaiJingLong** [comment]
> 新写一个页面用来播放全屏，然后通过和ios原生交互来动态改变这个页面是否可以全屏。
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "MessiMercy"<notifications@github.com>; 发送时间: 2019年7月3日(星期三) 上午10:39 收件人: "CaiJingLong/flutter_ijkplayer"<flutter_ijkplayer@noreply.github.com>; 抄送: "陈洲洲"<474116207@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [CaiJingLong/flutter_ijkplayer] iOS全屏幕的问题,因为项目不能旋转屏幕,所以设置了xcode只能竖屏,点击全屏就闪退 (#62) 同求解决办法 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

这个其实是一个可行的方案, 但是需要使用者对原生代码做一些修改, 可能会造成其他的bug... 因为转屏的代码flutter官方现在的实现都还有问题... 所以确实是不太好办的事情

**Comment by programmerElephant** [comment]
这样实现遇到过一些问题,体现在自定义控制栏，由于我的控制栏内容很多，数据量大，所以在全屏和非全屏的时候数据同步出了不少问题。




------------------ 原始邮件 ------------------
发件人: "Caijinglong"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 下午4:23
收件人: "CaiJingLong/flutter_ijkplayer"<flutter_ijkplayer@noreply.github.com>;
抄送: "陈洲洲"<474116207@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CaiJingLong/flutter_ijkplayer] iOS全屏幕的问题,因为项目不能旋转屏幕,所以设置了xcode只能竖屏,点击全屏就闪退 (#62)



 
新写一个页面用来播放全屏，然后通过和ios原生交互来动态改变这个页面是否可以全屏。
 …
 ------------------ 原始邮件 ------------------ 发件人: "MessiMercy"notifications@github.com; 发送时间: 2019年7月3日(星期三) 上午10:39 收件人: "CaiJingLong/flutter_ijkplayer"flutter_ijkplayer@noreply.github.com; 抄送: "陈洲洲"474116207@qq.com;"Author"author@noreply.github.com; 主题: Re: [CaiJingLong/flutter_ijkplayer] iOS全屏幕的问题,因为项目不能旋转屏幕,所以设置了xcode只能竖屏,点击全屏就闪退 (#62) 同求解决办法 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
  
这个其实是一个可行的方案, 但是需要使用者对原生代码做一些修改, 可能会造成其他的bug... 因为转屏的代码flutter官方现在的实现都还有问题... 所以确实是不太好办的事情

**Comment by programmerElephant** [comment]
通过上一封email这样实现，在全屏和非全屏切换的时候能感受到明显的画面拉扯感.....




------------------ 原始邮件 ------------------
发件人: "Caijinglong"<notifications@github.com>;
发送时间: 2019年7月4日(星期四) 下午4:21
收件人: "CaiJingLong/flutter_ijkplayer"<flutter_ijkplayer@noreply.github.com>;
抄送: "陈洲洲"<474116207@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [CaiJingLong/flutter_ijkplayer] iOS全屏幕的问题,因为项目不能旋转屏幕,所以设置了xcode只能竖屏,点击全屏就闪退 (#62)




说实话... 我个人没有想到特别好的办法
 直接在竖屏情况下通过"旋转"IjkPlayer 90度(270度)并且充满全屏肯定是一个办法, 但是这种情况下可能不能隐藏系统的状态栏, 或者有其他问题, 比如在脑补未经验证的情况下个人感觉可能会有手势的问题
 
 
另外我因为最近有工作上的事情, 没有太多的时间解决这个问题, 所以这个问题可能会搁置一段时间, 后面我会通过一个配置选项来让用户主动"告诉"IjkPlayer是使用"旋转"的方式来显示全屏, 还是现在这种强制横屏的方式

**Comment by CaiJingLong** [comment]
使用RotateBox来实现全屏, 可以尝试一下0.3.1版本.

**Comment by dmlzj** [comment]
不需要在xcode设置禁止旋转，flutter有可以强制竖屏的，但是点了全屏后，再退出来的时候需要再次设置下强制竖屏，需要作者把退出全屏的方法暴露出来监听下！！

**Comment by dmlzj** [comment]
我找我们组ios开发看了下这个问题，然后解决了，不确定是否会有其他问题，解决方式如下：
原代码：
![1](https://user-images.githubusercontent.com/3021601/63397669-ed7c4f80-c3fd-11e9-86dd-5659f79a8ff3.jpg)
修改后：
![2](https://user-images.githubusercontent.com/3021601/63397672-f3723080-c3fd-11e9-8745-a9df84b6c865.jpg)
改完后，可以旋转了，退出全屏也能旋转回去，而且方向锁定了！ @CaiJingLong

**Comment by CaiJingLong** [comment]
@dmlzj 作为通用型的插件 是不能这么改的..   因为并不是所有项目都是强制竖屏锁定的... 
其实最好的方式肯定是读取app本身的锁定配置来做这个事情, 但是我没有找到api 

你如果觉得需要"真全屏" 就是那个旋转过去的方式, 那你可能需要fork后自己改下

**Comment by dmlzj** [comment]
@CaiJingLong 嗯，通用型插件的话确实不能这样，不过初始化播放器的时候倒是可以加个参数配置下，如果需要强制竖屏的就这样处理，不需要的就按照之前的方式！
