### ISSUE TITLE
[Need help] About FullScreen

### ISSUE THREAD

**Issue by qq125183592** [CaiJingLong/flutter_ijkplayer#63]
有几个问题想咨询下大神

1、视频全屏后，能否修改退出全屏按钮的位置，statusWidgetBuilder在窗口播放时能在上面自定义内容，全屏发现无效果；

2、视频全屏后，物理返回是返回页面，而不只是退出全屏状态，这块能修改吗

**Comment by jendy2012** [comment]
1.在手机横向放置的时候，点退出全屏按钮，整个页面会变成横屏（在自动旋转打开的情况）。不开自动旋转没有这个问题。
2.有没有退出全屏的事件或者回调，目前因为获取不到全屏的context，外部无法关闭全屏页面。。

**Comment by CaiJingLong** [comment]
@qq125183592 
0.2.4版本是支持修改全屏UI的
当前的自定义控制器是基于以下部分实现的
https://github.com/CaiJingLong/flutter_ijkplayer/blob/6c28d5954425a812a135df07436b86825656c3c1/lib/src/widget/controller_widget_builder.dart#L17-L23

使用默认的控制器`DefaultIJKControllerWidget`作为控制器界面
全屏控制器是一个新开的界面,使用DefaultIJKControllerWidget中的`fullscreenControllerWidgetBuilder`属性提供的返回值(Widget)作为全屏控制器的UI

这部分代码会回调到
https://github.com/CaiJingLong/flutter_ijkplayer/blob/6c28d5954425a812a135df07436b86825656c3c1/lib/src/widget/controller_widget_builder.dart#L722-L728

基于以上部分的说明, 你需要自定义全屏的UI需要以下几个步骤

使用IJKPlayer的`controllerWidgetBuilder`属性, 返回一个`DefaultIJKControllerWidget`

这个DefaultIJKControllerWidget 使用并配置属性
```dart
DefaultIJKControllerWidget(
    controller: controller,
    currentFullScreenState: true,
);
```

具体的可以查看example
https://github.com/CaiJingLong/flutter_ijkplayer/blob/e5b0182c803fa9f82cdebdb3c8b5e638346a0b79/example/lib/page/full_screen.dart#L187-L238

因为`DefaultIJKControllerWidget`对外暴露的是整体封装过的Widget, 所以单独修改全屏按钮的位置,图标大小等属性可能都需要你复制一份`DefaultIJKControllerWidget`的代码到自己的项目中并修改为你的`MyIJKControllerWidget`


----

第二个没有看懂, "返回页面"和"退出全屏"有什么不同?

**Comment by CaiJingLong** [comment]
@jendy2012  
1. 当前的退出全屏后会做的操作是接触锁定屏幕方向, 剩下的就是你的应用行为了
2. 退出全屏理论上直接Navigator.pop(context); 就可以了, context传外部的也是可行的.

**Comment by qq125183592** [comment]
> @jendy2012
> 
> 1. 当前的退出全屏后会做的操作是解除锁定屏幕方向, 剩下的就是你的应用行为了, 默认情况下的进入全屏和退出全屏的回调我会在下版本加入项目中
> 2. 退出全屏理论上直接`Navigator.pop(context);` 就可以了, context传外部的也是可行的.

第2个问题是这样的：

A页面到B页面，B页面看视频。

按需求在B页面全屏，点击返回按钮应该是跳出全屏，在B页面窗口继续播放；

目前的效果是B页面全屏观看时，点击返回就跳到了A页面。

**Comment by CaiJingLong** [comment]
> 第2个问题是这样的：
> 
> A页面到B页面，B页面看视频。
> 
> 按需求在B页面全屏，点击返回按钮应该是跳出全屏，在B页面窗口继续播放；
> 
> 目前的效果是B页面全屏观看时，点击返回就跳到了A页面。

可能是我理解力不够
我梳理一下:
在1楼时, 你的需求是: 物理返回键需要完全退出全屏并关闭页面, 但是退出全屏的按钮依然是退出全屏继续播放

到了上面一楼的时候.你的需求变成了按返回按钮需要退出全屏, 在B页面继续播放

---

然后在1楼时, 这个库全屏时是退出全屏并关闭B页,到了上面一楼的时候刚好反过来, 变成了退出全屏而不关闭页面


所以你真实的需求你自己有没有搞清楚

**Comment by qq125183592** [comment]
> > 第2个问题是这样的：
> > A页面到B页面，B页面看视频。
> > 按需求在B页面全屏，点击返回按钮应该是跳出全屏，在B页面窗口继续播放；
> > 目前的效果是B页面全屏观看时，点击返回就跳到了A页面。
> 
> 可能是我理解力不够
> 我梳理一下:
> 在1楼时, 你的需求是: 物理返回键需要完全退出全屏并关闭页面, 但是退出全屏的按钮依然是退出全屏继续播放
> 
> 到了上面一楼的时候.你的需求变成了按返回按钮需要退出全屏, 在B页面继续播放
> 
> 然后在1楼时, 这个库全屏时是退出全屏并关闭B页,到了上面一楼的时候刚好反过来, 变成了退出全屏而不关闭页面
> 
> 所以你真实的需求你自己有没有搞清楚

我的需求只有一种，可能沟通上我们没一致，😄

我现在确认下，**需要的是点击返回只退出全屏，而不要退出这个页面了**

**Comment by qq125183592** [comment]
第一个问题已经搞定，自己修改了UI，感谢作者！

**Comment by CaiJingLong** [comment]
关于全屏和物理返回键的问题: 根据我当前的测试,在全屏后目前的情况下是只退出, 我使用的测试范例来自于当前的example

可以查看网盘:  
链接: https://pan.baidu.com/s/1x-HciUbRmuOcMFNLpA3DEw 提取码: exy4 复制这段内容后打开百度网盘手机App，操作更方便哦

**Comment by qq125183592** [comment]
> 关于全屏和物理返回键的问题: 根据我当前的测试,在全屏后目前的情况下是只退出全屏,不关闭原始IJKPlayer所在的页面, 我使用的测试范例来自于当前的example.
> 
> 可以查看网盘:
> 链接: https://pan.baidu.com/s/1x-HciUbRmuOcMFNLpA3DEw 提取码: exy4 复制这段内容后打开百度网盘手机App，操作更方便哦

谢谢，我学习下～

**Comment by qq125183592** [comment]
我先关闭了，如果范例都没问题，我再找下这边场景有没影响，感谢耐心解答。
