### ISSUE TITLE
[Need help]release版本 app闪退

### ISSUE THREAD

**Issue by YesXiamo** [CaiJingLong/flutter_ijkplayer#64]
** 简单描述 **
用flutter的pakages导入此库，使用此库后，debug版本可用，flutter build apk出来的app直接启动页闪退，注释此库，正常运行，是需要什么设置吗

** 辅助信息 **

**Comment by CaiJingLong** [comment]
从描述来看是so库的问题,你可能需要查询apk中包含的so库是否完整
本库包含armv7和v8a的so库, 所以可能是其他的库不完整

具体的原因可以搜索一下 abiFilters的设置
或使用 flutter build apk --target-platform android-arm打包

---

不过这只是一种可能,都是个人猜测, 你需要使用adb logcat的日志信息来确定真实的问题, 在得到更多的信息前可能无法解决这个问题

**Comment by YesXiamo** [comment]
十分感谢，找到问题了，通过logcat发现
**java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.logintest1release-J8z-BtdT1XMRtof-MAQwqA==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.logintest1release-J8z-BtdT1XMRtof-MAQwqA==/lib/arm64, /data/app/com.example.logintest1release-J8z-BtdT1XMRtof-MAQwqA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]] couldn't find **"libflutter.so"****
原因是flutter没有arm64-v8a的库，在app\build. gradle    abiFilters中写入
**abiFilters 'armeabi-v7a'**
解决问题，但是有个疑问，为什么同样不修改之前在android5.1设备上能运行，8.1的设备不行，报如上错误，是因为8.1自动使用v8a的库吗，
