### ISSUE TITLE
[Need help]求助，加密的m3u8视频无法播放，不知为何？

### ISSUE THREAD

**Issue by GakkiiSmile** [CaiJingLong/flutter_ijkplayer#65]
求助，ios平台加密的m3u8视频无法播放，安卓平台可以，不知为何？

ios logs:
ijkmediaplayer version : k0.8.8-7-g96d0bd3e===== custom modules begin =====
register demuxer : ijklivehook
===== custom modules end =====
av_version_info: ff3.4--ijk0.8.7--20180103--001
ijk_version_info: k0.8.8-7-g96d0bd3e
ijkmp_set_inject_opaque(0x281596640)
ijkmp_set_inject_opaque()=void
ijkmp_set_ijkio_inject_opaque(0x281596640)
ijkmp_set_ijkio_inject_opaque()=void
2019-05-18 22:06:03.477280+0800 Runner[2616:827368] OK setup GL
ijkmp_ios_set_view(glView=0x14e920f70)
ijkmp_ios_set_view(glView=0x14e920f70)=void
ijkmp_set_data_source
ijkmp_prepare_async()
ijkmp_prepare_async()=0
FFP_MSG_ERROR: 0
flutter: (w)Ijk:play error , errorValue : 0

**Comment by GakkiiSmile** [comment]
例如： https://www.radiantmediaplayer.com/media/rmp-segment/bbb-abr-aes/playlist.m3u8

**Comment by 0-php** [comment]
应该是你视频本身的问题吧你的m3u8文件和 加密的域名是不是同一个地址 我用第三方工具也不能播放你的视频

**Comment by GakkiiSmile** [comment]
> 应该是你视频本身的问题吧你的m3u8文件和 加密的域名是不是同一个地址 我用第三方工具也不能播放你的视频

1.是同域名的，ios不能播放，安卓上可以播放。
2.在电脑上IINA直接测试这个m3u8地址也是正常的。
3.使用flutter官方的video-player，ios和安卓平台都正常。

**Comment by Seifon** [comment]
> > 应该是你视频本身的问题吧你的m3u8文件和 加密的域名是不是同一个地址 我用第三方工具也不能播放你的视频
> 
> 1.是同域名的，ios不能播放，安卓上可以播放。
> 2.在电脑上IINA直接测试这个m3u8地址也是正常的。
> ![image](https://user-images.githubusercontent.com/18532706/57977695-6e5b3200-7a30-11e9-8868-e5d19275b3f7.png)
> 3.使用flutter官方的video-player，ios和安卓平台都正常。
> 4.直接使用ios上的Safari 也是可以正常播放的。
> ![image](https://user-images.githubusercontent.com/18532706/57977726-3dc7c800-7a31-11e9-97cd-50de2d59c980.png)

我也出现了这种问题。在IOS上能够播放，在安卓上不能播放。后来只能折中方案，Android上用exo，IOS上用IJK，只是要写两套UI控件

**Comment by Seifon** [comment]
这种问题很奇怪，我看bilibili_ijk项目有人说是因为软硬解的问题，切换软解就可以解决这个问题。你可以试试

**Comment by CaiJingLong** [comment]
我这里做的仅仅是做android 和iOS 的sdk的对接,如果出现了播放问题, 还是需要去bilibili/ijkplayer寻找有没有解决方案

**Comment by GakkiiSmile** [comment]
> 我这里做的仅仅是做android 和iOS 的sdk的对接,如果出现了播放问题, 还是需要去bilibili/ijkplayer寻找有没有解决方案

谢谢 兄得，我找到问题了，因为ijk编译配置少了mpeg2video解码器，所以我重新编译了一下，问题就解决了。

> 这种问题很奇怪，我看bilibili_ijk项目有人说是因为软硬解的问题，切换软解就可以解决这个问题。你可以试试

重新编译了配置解决了。谢谢啊。

**Comment by Seifon** [comment]
> > 我这里做的仅仅是做android 和iOS 的sdk的对接,如果出现了播放问题, 还是需要去bilibili/ijkplayer寻找有没有解决方案
> 
> 谢谢 兄得，我找到问题了，因为ijk编译配置少了mpeg2video解码器，所以我重新编译了一下，问题就解决了。
> 
> > 这种问题很奇怪，我看bilibili_ijk项目有人说是因为软硬解的问题，切换软解就可以解决这个问题。你可以试试
> 
> 重新编译了配置解决了。谢谢啊。

你编译的是哪一个配置呢？

**Comment by GakkiiSmile** [comment]
> > > 我这里做的仅仅是做android 和iOS 的sdk的对接,如果出现了播放问题, 还是需要去bilibili/ijkplayer寻找有没有解决方案
> > 
> > 
> > 谢谢 兄得，我找到问题了，因为ijk编译配置少了mpeg2video解码器，所以我重新编译了一下，问题就解决了。
> > > 这种问题很奇怪，我看bilibili_ijk项目有人说是因为软硬解的问题，切换软解就可以解决这个问题。你可以试试
> > 
> > 
> > 重新编译了配置解决了。谢谢啊。
> 
> 你编译的是哪一个配置呢？

在你的配置基础上的--list-decoders 下面增加了
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mpeg2video"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=ac3"

--list-demuxers增加了
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=ac3"

**Comment by yaooort** [comment]
@GakkiiSmile 能不能发我一下iOS编译文件。网太慢了编译不过来

**Comment by CaiJingLong** [comment]
这个解决方案可能可以适合很多播放的问题

使用 ffprobe 可以查看具体的编码和封装方式

事实上, 默认情况下不可能也不应该提供所有编解码器
