### ISSUE TITLE
加载视频，是不是有设置超时时间呢？

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#66]
播放视频的源，因为加载比较耗时，两三秒就报错了

```
    "LocalDataTask <053C8B40-B031-49C0-A3FE-6A01DBE8A42E>.<1>"
)} [303]
	[C2.1 C141AF96-99E6-49A0-969B-64E5DB49964B 192.168.1.108:54305<->124.192.164.41:443]
	Connected Path: satisfied (Path is satisfied), interface: en1
	Duration: 10.245s, DNS @0.005s took 0.016s, TCP @0.024s took 0.044s, TLS took 0.113s
	bytes in/out: 4002/756, packets in/out: 7/7, rtt: 0.041s, retransmitted packets: 0, out-of-order packets: 0
```

**Comment by CaiJingLong** [comment]
https://github.com/CaiJingLong/flutter_ijkplayer/blob/91068768e58b7644ae9adb640ca9dcdd576aabd0/ios/Classes/CoolFlutterIJK.m#L161
iOS 部分是默认的Option

https://github.com/CaiJingLong/flutter_ijkplayer/blob/91068768e58b7644ae9adb640ca9dcdd576aabd0/android/src/main/java/top/kikt/ijkplayer/Ijk.kt#L42-L50
android部分有一些设置, 但是没看出哪个像是超时时间

**Comment by Seifon** [comment]
> https://github.com/CaiJingLong/flutter_ijkplayer/blob/91068768e58b7644ae9adb640ca9dcdd576aabd0/ios/Classes/CoolFlutterIJK.m#L161
> 
> 
> iOS 部分是默认的Option
> https://github.com/CaiJingLong/flutter_ijkplayer/blob/91068768e58b7644ae9adb640ca9dcdd576aabd0/android/src/main/java/top/kikt/ijkplayer/Ijk.kt#L42-L50
> 
> 
> android部分有一些设置, 但是没看出哪个像是超时时间

如果自己加入的option，会覆盖Ijk.kt里面的option吗？比如我想改成软解码

**Comment by CaiJingLong** [comment]
参考readme中的自定义option
