### ISSUE TITLE
rtsp播放

### ISSUE THREAD

**Issue by lp7799** [CaiJingLong/flutter_ijkplayer#67]
播放rtsp流黑屏，只有进度条正常

**Comment by CaiJingLong** [comment]
大部分播放黑屏或其他的问题我这里解决不了

但是你可以留下rtsp的公网可用Url, 有无声音等情况.
是iOS还是android,  插件版本等情况看看是否有其他人能帮助解决.

**Comment by CaiJingLong** [comment]
因为没有公网可用的url, 我这里无法测试, 依照置顶issue规则暂时关闭, 如果有后续疑问, 请重新open

**Comment by CaiJingLong** [comment]
你可以查看 #85 提供的方法能否解决你的问题.
如果确定这个方法可以解决, 我可以将重新编译后的库放入下一个版本更新
