### ISSUE TITLE
[Bug] ios模拟器iphone6使用本地视频播放会黑屏

### ISSUE THREAD

**Issue by zszen** [CaiJingLong/flutter_ijkplayer#69]
**描述一下你遇到的bug**
按照例子asset_page方法添加播放器，能读取到秒，并且能开始播放，但是就无法看到图像，本地视频，我替换成例子的视频也是黑屏

**Desktop (please complete the following information):**

**flutter版本**
v1.5.4-hotfix.2

```bash

```

**插件版本**
flutter_ijkplayer: 0.2.4

**截图**
![Snip20190521_1](https://user-images.githubusercontent.com/1890538/58039501-8ed8d880-7b65-11e9-9dda-e966bddc412f.png)

**Comment by CaiJingLong** [comment]
See README.
![image](https://user-images.githubusercontent.com/14145407/58084062-c8085b80-7bec-11e9-9b45-e13c64aa7c27.png)

**Comment by CaiJingLong** [comment]
这个并不是库的原因造成的, 而是flutter的Texture组件不支持iOS模拟器.

**Comment by zszen** [comment]
@CaiJingLong 十分感谢，没有仔细阅读，谢谢，我这里视频没带音频通道，所以我只看到了秒数，再次感谢
