### ISSUE TITLE
当使用tabbar切换tabbarview时会出现错误

### ISSUE THREAD

**Issue by zszen** [CaiJingLong/flutter_ijkplayer#70]
**描述一下你遇到的bug**
卡在  set textureId(int id) { 的 _textureIdController.add(id);这行， 提示
Exception has occurred.
NoSuchMethodError (NoSuchMethodError: The method 'add' was called on null.
Receiver: null
Tried calling: add(null))

**重现bug**
1. 创建Tabbar和 TabbarView，并创建三个横排按钮
![image](https://user-images.githubusercontent.com/1890538/58094928-605e0a80-7c04-11e9-93d9-b67ef4c08d96.png)
2. 将第二个tabbarview设置为视频播放
3. 从第一个tabbarview切换到第三个，这时候就100%会导致崩溃
代码使用的是例子里的，有做初始化和dispose销毁, build下代码为
```
return Container(
       child: IjkPlayer(
         mediaController: mvc,
       ),
    );
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - xcode simulator iphone6
 - 10.14.4 

**flutter版本**
v1.5.4-hotfix.2

**插件版本**
flutter_ijkplayer: 0.2.4

**截图**
如果有,请截图
![image](https://user-images.githubusercontent.com/1890538/58094684-e3cb2c00-7c03-11e9-81ea-4dbc82749545.png)

**Comment by CaiJingLong** [comment]
可以上传一份完整代码吗?

**Comment by CaiJingLong** [comment]
我猜测是TabView/Tabbar这样的控件结合生命周期的问题, 我需要一份可用代码, 实际运行一下, 看一下是库本身有问题, 还是使用方式有问题.

**Comment by zszen** [comment]
@CaiJingLong 等我弄一个放上来

**Comment by zszen** [comment]
只打包了lib assets和pubspec.yaml，只有这三个地方是动过的，从第一个tab切换到第三个就会出现这个bug，或者从第三个切换回第一个

[bugtest.zip](https://github.com/CaiJingLong/flutter_ijkplayer/files/3205701/bugtest.zip)

**Comment by CaiJingLong** [comment]
原因大概知道, TabView快速切换的情况下
dispose的调用过早

我会修复一下这个问题

**Comment by CaiJingLong** [comment]
Try use version `0.2.5`.

**Comment by zszen** [comment]
@CaiJingLong 测试了一下可以了，谢谢
