### ISSUE TITLE
视频上的按钮和循环播放问题求助

### ISSUE THREAD

**Issue by zszen** [CaiJingLong/flutter_ijkplayer#72]
** 简单描述 **
如何在普通播放下隐藏所有控制，并且视频支持循环，下面的代码可以去掉底部进度条和播放暂停全屏（全屏点击会闪退ios，不过我用不到），视频可以自动播放，但一开始会看到播放按钮，结束也会看到重播按钮。

需求就是不显示播放按钮和重播按钮，并且支持自动循环播放

** 辅助信息 **
```
IjkPlayer(
            mediaController: controller,
            controllerWidgetBuilder: (mediaController){
              return Container(); // 自定义
            },
          ),
```

**Comment by MeDeity** [comment]
关于循环播放问题,可以通过监听播放事件的完成进行处理:
demo中的 ControllerStreamUsagePage页面演示:
```java

  StreamSubscription subscription;
  subscriptPlayFinish() {
    subscription = controller.playFinishStream.listen((data) {
      showToast(currentI18n.playFinishToast);
      controller.play();//add this
    });
  }
```

**Comment by CaiJingLong** [comment]
> 关于循环播放问题,可以通过监听播放事件的完成进行处理:
> demo中的 ControllerStreamUsagePage页面演示:
> 
> ```java
>   StreamSubscription subscription;
>   subscriptPlayFinish() {
>     subscription = controller.playFinishStream.listen((data) {
>       showToast(currentI18n.playFinishToast);
>       controller.play();//add this
>     });
>   }
> ```

楼上正解 😄

Example 代码连接在这里 https://github.com/CaiJingLong/flutter_ijkplayer/blob/f66bd338e7d329c2977751f5a8fe6aa88f94d456/example/lib/page/controller_stream_use.dart#L131-L137

**Comment by zszen** [comment]
@CaiJingLong 👍

**Comment by songjhh** [comment]
但是一开始加载时的播放键还是会闪现一下
