### ISSUE TITLE
NoSuchMethodError: The method 'getTargetSeek' was called on null. Receiver: null Tried calling: getTargetSeek(Instance of 'DragEndDetails')

### ISSUE THREAD

**Issue by Seifon** [CaiJingLong/flutter_ijkplayer#73]
最近bugly收到几个客户端会出现这个异常：

NoSuchMethodError: The method 'getTargetSeek' was called on null. Receiver: null Tried calling: getTargetSeek(Instance of 'DragEndDetails')

异常发生位置：

```
void _onHorizontalDragEnd(DragEndDetails details) async {
    if (!widget.currentFullScreenState) {
      return;
    }

    hideTooltip();
    var targetSeek = _calculator.getTargetSeek(details);
    _calculator = null;
    await controller.seekTo(targetSeek);
    var videoInfo = await controller.getVideoInfo();
    if (targetSeek < videoInfo.duration) await controller.play();
  }
```

**Comment by CaiJingLong** [comment]
正常的使用不会出现这个问题, 但是大量的用户会出现各种偶发性的错误.
我会在这里加一个判断来限制可能出现的错误.

**Comment by CaiJingLong** [comment]
如果通过bugly接受到其他关于这个库的错误, 请一并提交, 我这里可以修改的会尽量修改

**Comment by CaiJingLong** [comment]
另外我观察到,  你粘贴到这里的代码和这个仓库的代码有所不同, 
可能是为了自己控制全屏下的逻辑

如果有需要, 可以参考下面的Example来修改, 现在支持使用自定义的全屏幕逻辑
https://github.com/CaiJingLong/flutter_ijkplayer/blob/f66bd338e7d329c2977751f5a8fe6aa88f94d456/example/lib/page/full_screen.dart#L213-L238

---

如果你坚持使用自己fork过的代码, 可以参考这个[修改](https://github.com/CaiJingLong/flutter_ijkplayer/pull/74/commits/8bd7586e8b6cac8a57863266233ff548d7a27609#diff-872ea3701147b2a8746b069c229fc7c9R333).
