### ISSUE TITLE
[Need help]iOS 使用自定义编译时运行报错

### ISSUE THREAD

**Issue by RayZhao1998** [CaiJingLong/flutter_ijkplayer#77]
使用自定义编译后的 framework 并修改 podspec 后运行会报如下错

![image](https://user-images.githubusercontent.com/22616933/58527507-7c197000-8205-11e9-86fb-cc308eacb061.png)

然后直接使用 0.2.6 版本的时候，查看了 `IJKFFMoviePlayerController.h` 中有对应的变量声明，请问如何解决

**Comment by CaiJingLong** [comment]
自定义编译需要使用我提供的项目中的源码, [文档在这](https://github.com/CaiJingLong/flutter_ijkplayer/blob/master/compile-cn.md). 
因为相对于原版的IJKPlayer, iOS端和android端都有改动以适应flutter.

![image](https://user-images.githubusercontent.com/14145407/58531016-6d39ba00-8213-11e9-9e66-24dc20c892e2.png)

**Comment by CaiJingLong** [comment]
至于本地无法使用的问题应该是不存在的, 因为我开发时iOS本地的文件使用的就是上面提供的git中的代码编译出来的本地仓库.

**Comment by RayZhao1998** [comment]
好的，因为我之前使用的是原版 IJKPlayer 编译的，应该是少了相关 Flutter 的内容，我用您提供的 IJKPlayer 源码再尝试一下。
