### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by DarkLT** [CaiJingLong/flutter_ijkplayer#81]
运行就报错
![image](https://user-images.githubusercontent.com/15633538/58946182-ed35c600-87b7-11e9-9793-b03bbeaccb8b.png)

**Comment by CaiJingLong** [comment]
看起来像是 kotlin的问题 更新你应用的kotlin版本

**Comment by CaiJingLong** [comment]
如果这个项目的example你能跑起来,就不是项目的问题.

**Comment by DarkLT** [comment]
感谢，果然是kotlin的问题
