### ISSUE TITLE
[Need help] 模拟器可以运行，真机报错Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by hehe2015** [CaiJingLong/flutter_ijkplayer#82]
Describe your needs

Undefined symbols for architecture arm64:
  "_IJKMPMoviePlayerVideoRotationRotateUserInfoKey", referenced from:
      -[CoolIjkNotifyChannel movieRotationChange:] in flutter_ijkplayer(CoolIjkNotifyChannel.o)
  "_IJKMPMoviePlayerVideoRotationNotification", referenced from:
      -[CoolIjkNotifyChannel registerObserver] in flutter_ijkplayer(CoolIjkNotifyChannel.o)
      -[CoolIjkNotifyChannel unregisterObservers] in flutter_ijkplayer(CoolIjkNotifyChannel.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

请问这是什么问题？

**Comment by CaiJingLong** [comment]
运行example?还是自己的代码?

**Comment by CaiJingLong** [comment]
自定义编译选项参考example

**Comment by hehe2015** [comment]
自己的项目中直接引入
dependencies:
  flutter_ijkplayer: ^0.2.6
android 真机模拟器都可用
ios 模拟器可用，真机报上面的错误
请问ios需要做别的处理吗？比如编译

**Comment by CaiJingLong** [comment]
看看这个: https://github.com/CaiJingLong/flutter_ijkplayer/issues/22#issuecomment-481976222

**Comment by CaiJingLong** [comment]
我不知道是不是这个原因, 因为那个错误信息是armv7的问题 而你这个是arm64的

如果example的运行没有问题, 可能你需要提供一个报错的完整代码库给我, 附件或者仓库都可以.

**Comment by hehe2015** [comment]
下载后跑example是可以的，然后我就把咱们的项目工程拷贝到这里改下 pubspec.yaml 
flutter_ijkplayer:
    path: ../
这样可以用，不知道是什么原因

**Comment by CaiJingLong** [comment]
参照我上面回复的#22修改可能有用
