### ISSUE TITLE
[Need help] iOS 端 rtsp 流无法正常播放

### ISSUE THREAD

**Issue by RayZhao1998** [CaiJingLong/flutter_ijkplayer#85]
相同 rtsp 流在 Android 端可以播放，iOS 端无法播放，控制台输出 `FFP_MSG_ERROR: 0`，rtsp 流地址：rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov

**Comment by RayZhao1998** [comment]
已解决，不确定是不是这个原因导致的，根据 [ijkplayer开启rtsp,并且支持录制和截图功能](https://www.jianshu.com/p/8078446fdbe6) 这篇文章中的描述，`module-rtsp.sh` 中缺少了这两个选项：

```
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mjpeg"
export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mjpeg"
```

我添加了这两个选项后重新编译出来的 framework 放到项目中是可以跑的。

但不确定是否是这个问题。

**Comment by CaiJingLong** [comment]
感谢反馈, 有别的朋友也有rtsp的问题,  我看那个朋友能否给出回应, 如果确定是标准的解决方案, 我尝试用这个选项重新编译framework和so

**Comment by AgustLite** [comment]
> Resolved, not sure if this is the cause, [open rtsp](https://www.jianshu.com/p/8078446fdbe6) according to [ijkplayer, and support recording and screenshot function](https://www.jianshu.com/p/8078446fdbe6)`module-rtsp.sh` . These two options are missing from the description in this article :
> 
> ```
> export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mjpeg"
> export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mjpeg"
> ```
> 
> After I added these two options, the recompiled framework can be run in the project.
> 
> But not sure if this is the problem.

that is true, tried it and worked fine when i recompiled the framework. but the problem it play from rtsp which the source is from cctv live stream. it will freeze after around 50 second . anyone have a solution?

**Comment by CaiJingLong** [comment]
> > Resolved, not sure if this is the cause, [open rtsp](https://www.jianshu.com/p/8078446fdbe6) according to [ijkplayer, and support recording and screenshot function](https://www.jianshu.com/p/8078446fdbe6)`module-rtsp.sh` . These two options are missing from the description in this article :
> > ```
> > export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-decoder=mjpeg"
> > export COMMON_FF_CFG_FLAGS="$COMMON_FF_CFG_FLAGS --enable-demuxer=mjpeg"
> > ```
> > 
> > 
> > After I added these two options, the recompiled framework can be run in the project.
> > But not sure if this is the problem.
> 
> that is true, tried it and worked fine when i recompiled the framework. but the problem it play from rtsp which the source is from cctv live stream. it will freeze after around 50 second . anyone have a solution?

Maybe you can find it in [bilibili/ijkplayer](https://github.com/bilibili/ijkplayer/issues)
