### ISSUE TITLE
[Need help]symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by YourksChan** [CaiJingLong/flutter_ijkplayer#86]
Error output from Xcode build:
↳
    2019-06-15 16:44:05.072 xcodebuild[70124:2560509]  DTDeviceKit: deviceType from 00008020-001A71A13C8400XX was NULL
    ** BUILD FAILED **

Xcode's output:
↳
    ld: warning: ignoring file /Users/xxx/AndroidStudioProjects/xxx/ios/Pods/FlutterIJK/IJKMediaFramework.framework/IJKMediaFramework, missing required architecture armv7 in file /Users/xxx/AndroidStudioProjects/xxx/ios/Pods/FlutterIJK/IJKMediaFramework.framework/IJKMediaFramework (3 slices)
    Undefined symbols for architecture armv7:
      "_OBJC_CLASS_$_IJKFFOptions", referenced from:
          objc-class-ref in libflutter_ijkplayer.a(CoolFlutterIJK.o)
      "_IJKMPMoviePlayerVideoRotationRotateUserInfoKey", referenced from:
          -[CoolIjkNotifyChannel movieRotationChange:] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerVideoRotationNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerPlaybackStateDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerPlaybackDidFinishReasonUserInfoKey", referenced from:
          -[CoolIjkNotifyChannel moviePlayBackFinish:] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMoviePlayerPlaybackDidFinishNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_OBJC_CLASS_$_IJKFFMoviePlayerController", referenced from:
          objc-class-ref in libflutter_ijkplayer.a(CoolFlutterIJK.o)
      "_IJKMPMoviePlayerLoadStateDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
      "_IJKMPMediaPlaybackIsPreparedToPlayDidChangeNotification", referenced from:
          -[CoolIjkNotifyChannel registerObserver] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
          -[CoolIjkNotifyChannel unregisterObservers] in libflutter_ijkplayer.a(CoolIjkNotifyChannel.o)
    ld: symbol(s) not found for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Could not build the precompiled application for the device.

Error launching application on iPhone.

**Comment by CaiJingLong** [comment]
Look like https://github.com/CaiJingLong/flutter_ijkplayer/issues/22#issuecomment-481976222

**Comment by CaiJingLong** [comment]
Close it.
If you still have a problem, you can reopen it.
