### ISSUE TITLE
Custom headers in ijplayer

### ISSUE THREAD

**Issue by morchidnb** [CaiJingLong/flutter_ijkplayer#88]
Please Is there any way to add http header for the Ijplayer in flutter ?

**Comment by CaiJingLong** [comment]
Support headers, but I don't add it at README. I will add the usage in readme.

https://github.com/CaiJingLong/flutter_ijkplayer/blob/fa9228d55d441c06cede45dade25dafa076a96b5/lib/src/controller/datasoure.dart#L29-L36

https://github.com/CaiJingLong/flutter_ijkplayer/blob/fa9228d55d441c06cede45dade25dafa076a96b5/lib/src/controller/controller.dart#L94-L106

**Comment by morchidnb** [comment]
Thanks for the plugin and for the help, any simple example for usage please ?

**Comment by CaiJingLong** [comment]
Clone the repository and run example.

**Comment by morchidnb** [comment]
thanks I figured out, very helpful plugin and support ... big thumbs up :)
