### ISSUE TITLE
[Need help] android编译时报错

### ISSUE THREAD

**Issue by shetz163** [CaiJingLong/flutter_ijkplayer#91]
** 简单描述 **
在编译的时候会报错,使用example编译也还是会报这个错误,
flutter doctor -v的信息如下

[√] Flutter (Channel dev, v1.7.9, on Microsoft Windows [Version 10.0.18362.175], locale zh-CN)
    • Flutter version 1.7.9 at D:\flutter\sdk
    • Framework revision 8dbfc82bc7 (4 days ago), 2019-06-24 11:41:02 +0100
    • Engine revision 4444c9cb6c
    • Dart version 2.4.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at D:\flutter\android sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: D:\flutter\android\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[X] Visual Studio - develop for Windows
    X Visual Studio not installed; this is necessary for Windows development.
      Download at https://visualstudio.microsoft.com/downloads/.

[√] Android Studio (version 3.4)
    • Android Studio at D:\flutter\android
    • Flutter plugin version 34.0.2
    • Dart plugin version 183.5901
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[√] VS Code (version 1.35.1)
    • VS Code at C:\Users\<user>\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.1.0

[√] Connected device (3 available)
    • Pixel 3 XL • 1A5F0E2MA • android-arm64  • Android 9 (API 28)
    • Windows    • Windows   • windows-x64    • Microsoft Windows [Version 10.0.18362.175]
    • web        • web       • web-javascript • Google Chrome 75.0.3770.100

提示的错误是
e: D:\flutter\test\flutter_ijkplayer\android\src\main\java\top\kikt\ijkplayer\Ijk.kt: (21, 1): Class 'Ijk' is not abstract and does not implement abstract member @UiThread public abstract fun onMethodCall(@NonNull p0: MethodCall, @NonNull p1: MethodChannel.Result): Unit defined in io.flutter.plugin.common.MethodChannel.MethodCallHandler
e: D:\flutter\test\flutter_ijkplayer\android\src\main\java\top\kikt\ijkplayer\Ijk.kt: (100, 5): 'onMethodCall' overrides nothing

** 辅助信息 **

![image](https://user-images.githubusercontent.com/5582519/60316622-e278e600-999d-11e9-9fb5-434f581c2e18.png)

**Comment by CaiJingLong** [comment]
似乎是对于flutter最新版本的适配问题, 我会抽时间修复一下

**Comment by CaiJingLong** [comment]
Update version to 0.3.0.
