### ISSUE TITLE
[Bug??]example 在 iphone6上 第一个网络视频 卡顿很厉害 是因为Debug模式的原因还是?还有那个兔子的视频,网络连接的那个,播放是黑屏的.在安卓上是正常的.

### ISSUE THREAD

**Issue by epenli** [CaiJingLong/flutter_ijkplayer#94]
兔子视频 是 listview播放的那个 前两个是网络的 后一个是本地的 . 网络的黑屏有声音.本地的正常.

**Comment by CaiJingLong** [comment]
兔子视频 你观看下地址 有一个是外国地址 那个地址是flutter官方的video_player用的一个视频链接  
你如果是chrome浏览器 可以直接把这个链接复制到浏览器上  也会很慢 网络问题 那个资源在一个外国的小站点上

**Comment by CaiJingLong** [comment]
至于播放黑屏 就不好说了
