### ISSUE TITLE
'IJKMediaFramework/IJKMediaFramework.h' file not found[Bug]

### ISSUE THREAD

**Issue by virskor** [CaiJingLong/flutter_ijkplayer#95]
**描述一下你遇到的bug**
描述一下你的bug
ios build bug 模拟器调试运行时正常

#import <IJKMediaFramework/IJKMediaFramework.h>
'IJKMediaFramework/IJKMediaFramework.h' file not found

Xcode's output:
↳
    In file included from
    /Users/virs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ijkplayer-0.3.0/ios/Classes/CoolFlutterIjkManager.m:6:
    In file included from
    /Users/virs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ijkplayer-0.3.0/ios/Classes/CoolFlutterIJK.h:7:
    /Users/virs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_ijkplayer-0.3.0/ios/Classes/CoolIjkNotifyChannel.h:7:9: fatal
    error: 'IJKMediaFramework/IJKMediaFramework.h' file not found
    #import <IJKMediaFramework/IJKMediaFramework.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**重现bug**

通过什么样的步骤可以重现:
flutter run --release

**Desktop (please complete the following information):**

**flutter版本**
使用 `$ flutter doctor -v` 并粘贴详细的信息到这里,如果是特定机型的bug,请包含设备信息
[✓] Flutter (Channel stable, v1.5.4-hotfix.2, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.5.4-hotfix.2 at /Users/virs/flutter
    • Framework revision 7a4c33425d (10 周前), 2019-04-29 11:05:24 -0700
    • Engine revision 52c7a1e849
    • Dart version 2.3.0 (build 2.3.0-dev.0.5 a1668566e5)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/virs/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 28.0.3
    ✗ Android SDK file not found: /Users/virs/Library/Android/sdk/platforms/android-29/android.jar.
    • Try re-installing or updating your Android SDK,
      visit https://flutter.dev/setup/#android-setup for detailed instructions.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • ios-deploy 1.9.4
    • CocoaPods version 1.6.1

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.3.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[!] IntelliJ IDEA Community Edition (version 2018.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.36.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[!] Proxy Configuration
    • HTTP_PROXY is set
    ! NO_PROXY is not set

[✓] Connected device (1 available)
    • 张威的 iPhone • 029252aa59e25c34188ac565344af93858a917b1 • ios • iOS 12.3.1

```bash

```

**插件版本**

0.3.0

**截图**
如果有,请截图
![image](https://user-images.githubusercontent.com/16968535/60757264-fcb86100-a03a-11e9-8e23-085e5706bdd4.png)
![image](https://user-images.githubusercontent.com/16968535/60757273-08a42300-a03b-11e9-8d48-a86772e65bab.png)

**Comment by CaiJingLong** [comment]
有相对完整的项目吗, 你可以尝试使用这个仓库自带的exmaple 看看是否有相应的问题

**Comment by CaiJingLong** [comment]
暂时先关闭, 可以提供完整Example的话, 你可以重新开启.

**Comment by virskor** [comment]
Hello 通过本地引入Framework可以解决这个问题
