### ISSUE TITLE
如何添加字幕 [Need help]

### ISSUE THREAD

**Issue by weiwill** [CaiJingLong/flutter_ijkplayer#96]
RT

**Comment by CaiJingLong** [comment]
外挂字幕吗?  目前插件没有支持字幕功能,  另外,据说bilibili/IJKPlayer本身外挂字幕的支持不太好, 所以这个插件没有做字幕的对接

建议你可以分析一下字幕格式, 一般字幕的格式都会比较简单, 通过一些正则配合Text和时间信息来实现自己的字幕插件,并且覆盖在Texture前即可

**Comment by weiwill** [comment]
感谢回复，是有大概思路，但是认为有支持更好
