### ISSUE TITLE
[Feature request]求助怎么给视频默认背景占位图，placeholder这种

### ISSUE THREAD

**Issue by yeoshine** [CaiJingLong/flutter_ijkplayer#97]
rt，多谢

**Comment by CaiJingLong** [comment]
[README](https://github.com/CaiJingLong/flutter_ijkplayer#%E6%A0%B9%E6%8D%AE%E5%BD%93%E5%89%8D%E7%8A%B6%E6%80%81%E6%9E%84%E5%BB%BA%E4%B8%80%E4%B8%AA-widget)

使用这个方法, 根据当前视频状态呈现不同的界面, 可以在某种意义上实现placeholder的概念.

**Comment by yeoshine** [comment]
> [README](https://github.com/CaiJingLong/flutter_ijkplayer#%E6%A0%B9%E6%8D%AE%E5%BD%93%E5%89%8D%E7%8A%B6%E6%80%81%E6%9E%84%E5%BB%BA%E4%B8%80%E4%B8%AA-widget)
> 
> 使用这个方法, 根据当前视频状态呈现不同的界面, 可以在某种意义上实现placeholder的概念.

已经按这个方法解决，多谢

**Comment by aerokwok** [comment]
如果要是播放音频的时候，有占位图，还能控制音频，应该怎么做呢？

**Comment by CaiJingLong** [comment]
@aerokwok 
如果是单纯播放音频而项目中没有播放视频的需求 建议使用一个单独的音频播放器以减小应用体积

单纯从这个库来说仅音频播放, 可以考虑只使用controller来实现播放的过程, 界面随意自定义即可

**Comment by aerokwok** [comment]
音视频都要播放，昨晚我把几个控制层设成透明，在外部解决了




在2019年10月25日 08:33，Caijinglong 写道：

@aerokwok
如果是单纯播放音频而项目中没有播放视频的需求 建议使用一个单独的音频播放器以减小应用体积

单纯从这个库来说仅音频播放, 可以考虑只使用controller来实现播放的过程, 界面随意自定义即可
