### ISSUE TITLE
[Need help]怎么在全屏之后左上角出现个返回按钮

### ISSUE THREAD

**Issue by yeoshine** [CaiJingLong/flutter_ijkplayer#99]
求助，怎么在全屏之后左上角出现个返回按钮，我看现在没有，多谢

![WechatIMG2](https://user-images.githubusercontent.com/4662777/60952574-16ed8a00-a32e-11e9-85ab-0b32dcfa5748.jpeg)

**Comment by yeoshine** [comment]
横竖屏都包含返回那种

**Comment by CaiJingLong** [comment]
查看文档 自定义控制UI

**Comment by yeoshine** [comment]
好的，已经实现
